#+TITLE: Cesar's Org-Based Literate Programming Toolkit
#+AUTHOR: Cesar Crusius
#+STARTUP: indent
#+PROPERTY: header-args :comments yes :noweb no-export :padline no :tangle-mode (identity #o555) :tangle no :mkdirp yes

* Cesar Crusius' Org-Based Literate Programming Toolkit

I wrote these tools originally in order to have a better way of
writing my $\TeX$ macros, specifically those that involve a lot of Lua
code. The =WEB= and =CWEB= tools were not language agnostic, and other
tools either had no Windows binaries available, or did not generate
plain $\TeX$ documentation. Since writing simple literate programming
weavers and tanglers is not too hard, I went ahead and wrote my own.

Years down the road, I had switched all of my computing configurations
to literate programming in Org mode, which provided a much better
editing environment. There were two problems: Emacs own weaving got
exceedingly slow, and I wanted to export my files to plain $\TeX$
files that used the =cwebmac= macros.  The result is this Org-based
set of tools.

The parser accepts a subset of the complete Org syntax, and expects a
certain structure that mimics what you would find in a =CWEB= file.

* Main Sections

#+NAME: Common-ccweb-code
#+BEGIN_SRC haskell
<<Language-features>>
<<Imports>>
<<Document data model>>
<<Pretty printing>>
<<Logging>>
<<Parser>>
<<Command-line-options>>
#+END_SRC

#+NAME: Stack-preamble
#+BEGIN_SRC haskell :comments no
{- stack
  script
  --resolver lts-12.22
  <<stack-packages>>
-}
#+END_SRC

#+NAME: Imports
#+BEGIN_SRC haskell
import Control.Applicative ((<|>), (<**>), liftA2)
import Control.Monad (void, when)
import Control.Monad.State (State, get, modify, runState)
import Data.Foldable (foldlM, foldrM)
import Data.Char (isPrint, isSpace, ord)
import Data.List (intercalate, isPrefixOf)
import Data.Maybe (fromJust, isJust, mapMaybe)
import qualified Data.Map as Map
import GHC.Exts (IsList(..), groupWith, sortWith)
#+END_SRC

#+NAME: Language-features
#+BEGIN_SRC haskell
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE TypeFamilies #-}
#+END_SRC

#+NAME: stack-packages
#+BEGIN_SRC shell
--package containers
--package mtl
#+END_SRC

* A Basic Stack

I will need a stack in various places. Apart from the obvious
operations (~top~, ~push~, and ~pop~), I want to be able to resize the
stack, either removing elements, or replicating the top element until
the desired size is reached.

#+NAME: Parser
#+BEGIN_SRC haskell
newtype Stack a = Stack [a]

top :: Stack a -> a
top (Stack xs) = head xs

push :: a -> Stack a -> Stack a
push x (Stack xs) = Stack $ x:xs

pop :: Stack a -> Stack a
pop (Stack []) = error $ "popping empty stack"
pop (Stack (_:xs)) = Stack xs

resize :: Int -> Stack a -> Stack a
resize i (Stack xs)
  | i == l = Stack xs
  | i < l = Stack $ reverse . take i . reverse $ xs
  | i > l && l > 0 = Stack $ replicate (i - l) (head xs) ++ xs
  | otherwise = error $ "resizing empty stack"
  where
    l = length xs
#+END_SRC

* The Org Document Structure

#+NAME: Document data model
#+BEGIN_SRC haskell
data Document = Document
  { orgKeywords :: [Keyword]
  , orgSections :: [Section]
  }
#+END_SRC

#+NAME: Document data model
#+BEGIN_SRC haskell
data Keyword = AuthorKeyword Text
             | PropertyKeyword Properties
             | TitleKeyword Text
             | OtherKeyword String
#+END_SRC

#+NAME: Document data model
#+BEGIN_SRC haskell
data Section = Section
  { sectionHeadline :: Maybe Headline
  , sectionProps :: Properties
  , sectionDerivedProperties :: Properties
  , sectionDocumentation :: [Text]
  , sectionSourceBlock :: Maybe SourceBlock
  }
#+END_SRC

#+NAME: Document data model
#+BEGIN_SRC haskell
data Headline = Headline Int Text
#+END_SRC

#+NAME: Document data model
#+BEGIN_SRC haskell
data Text = Text [TextElement] deriving (Eq, Ord, Show)

data TextElement =
  Bold String
  | InlineCode String
  | Italics String
  | Plain String
  | StrikeThrough String
  | Verbatim String
  deriving (Eq, Ord, Show)
#+END_SRC

#+NAME: Document data model
#+BEGIN_SRC haskell
data SourceBlock = SourceBlock
  { blockName :: Maybe Text
  , blockLanguage :: String
  , blockProperties :: Property
  , blockDerivedProperties :: Property
  , blockLocation :: P.SourcePos
  , blockLines :: [CodeLine]
  }
#+END_SRC

#+NAME: Document data model
#+BEGIN_SRC haskell
type Property = Map.Map String SExpression
type Properties = Map.Map String Property
#+END_SRC

#+NAME: Document data model
#+BEGIN_SRC haskell
data SExpression =
  Atom String
  | Series [SExpression]
  | YesNo Bool
  deriving (Eq, Ord)
#+END_SRC

#+NAME: Document data model
#+BEGIN_SRC haskell
data CodeElement = Literal P.SourcePos String
                 | SectionReference P.SourcePos Text

data CodeLine = CodeLine P.SourcePos [CodeElement]
#+END_SRC

* Tangling

#+BEGIN_SRC haskell :tangle "bin/cctangle.hs" :tangle-mode (identity #o444)
<<Common-ccweb-code>>
<<Tangler>>
#+END_SRC

#+NAME: Tangler
#+BEGIN_SRC haskell
type Indent = String
#+END_SRC

#+NAME: Tangler
#+BEGIN_SRC haskell
data Line = LinePragma String P.SourcePos | Raw String

instance Show Line where
  show (Raw str) = str ++ "\n"
  show (LinePragma lang pos) = case linePragma lang pos of
                               [] -> ""
                               s -> s ++ "\n"

unindent :: Indent -> Line -> Line
unindent i (Raw s)
  | isPrefixOf i s = Raw $ drop (length i) s
  | otherwise = Raw s
unindent _ l = l

isRaw :: Line -> Bool
isRaw (Raw _) = True
isRaw _ = False
#+END_SRC

#+NAME: Tangler
#+BEGIN_SRC haskell
data TangleState = TangleState
  { document :: Document
  , indent :: String
  , blocks :: Stack SourceBlock
  }
#+END_SRC

#+NAME: Tangler
#+BEGIN_SRC haskell
type Tangler a = State TangleState a
#+END_SRC

#+NAME: Tangler
#+BEGIN_SRC haskell
class Tangle a where
  tangle :: a -> Tangler [Line]
#+END_SRC

Tangling a code block results in a list of /lines/. The first line is
not indented, and is appended to the previous code part on the same
line. The last line will be prepended to the next code part on the
same line.

#+NAME: Tangler
#+BEGIN_SRC haskell
instance Tangle SourceBlock where
  tangle block = do
    modify (\s -> s{ blocks = push block (blocks s) })
    ls <- concat <$> mapM tangle (blockLines block)
    modify (\s -> s{ blocks = pop (blocks s) })
    let pragma = LinePragma (blockLanguage block) (blockLocation block)
    case headerArg ":comments" block of
      Just (YesNo True) -> return (pragma : ls)
      _ -> return ls
#+END_SRC

Tangling a code line is a matter of tangling all of its elements and
stitching them together. This is complicated by two things:

- A single element can result in multiple lines if it is a reference
  expansion. It is not uncommon for a "code line" to expand into a
  large part of the entire program.
- Those lines have to be properly indented, which means I have to keep
  track of indentation as I go.

The mechanism used to handle those is a left fold that keeps track of
the current list of tangled lines. A new element is tangled and appended
to this list, and the indentation for the next element is given by the
last line.

The lines are kept in reverse order until the end for performance
considerations. I need to merge the current last line to the next
first line, and finding the last line of a list in Haskell is an
expensive operation.

#+NAME: Tangler
#+BEGIN_SRC haskell
instance Tangle CodeLine where
  tangle (CodeLine _ []) = do
    ind <- indent <$> get
    return [Raw ind]
  tangle (CodeLine _ elements) = do
    state <- get
    let block = top (blocks state)
        ind   = indent state
        pos = case head elements of
                (Literal p _) -> p
                (SectionReference p _) -> p
        pragma = LinePragma (blockLanguage block) pos
    ls <- reverse <$> foldlM revacc [Raw ind] elements
    modify (\s -> s{ indent = ind })
    case headerArg ":comments" block of
      Just (YesNo True) -> return $ pragma : ls
      _ -> return ls
      where
        revacc :: [Line] -> CodeElement -> Tangler [Line]
        revacc acc element = do
          let (pre, (Raw l:ls)) = break isRaw acc
          modify (\s -> s{ indent = replicate (length l) ' ' })
          (pre', (Raw l':ls')) <- break isRaw <$> tangle element
          return $
            reverse ls'
            ++ [Raw(l ++ l')]
            ++ reverse pre'
            ++ pre
            ++ ls
#+END_SRC

Tangling of code parts is the last piece of the puzzle. Literals are
easy, but code blocks need to have their first lines be /not/
indented, so one can have proper "inline" code blocks, such as

#+BEGIN_SRC c :tangle no
int main(void) { <<do everything>>; return 0; }
#+END_SRC

#+NAME: Tangler
#+BEGIN_SRC haskell
instance Tangle CodeElement where
  tangle (Literal _ s) = return [Raw s]
  tangle (SectionReference _ name) = do
    bs <- <<Gather code blocks named ~name~>> :: Tangler [SourceBlock]
    when (null bs) (error $ "source block not defined anywhere: " ++ show name)
    ls <- concat <$> mapM tangle bs :: Tangler [Line]
    ls' <- <<Unindent first line of ~ls~>>
    return ls'
--  if runProperty (commentsProperty $ codeBlockProperties parent)
--     then ls ++ [Location (codeBlockLanguage parent) loc]
--     else ls
#+END_SRC

#+NAME: Gather code blocks named ~name~
#+BEGIN_SRC haskell
filter (\b -> case (blockName b) of
               Nothing -> False
               Just t -> t == name)
  . mapMaybe sectionSourceBlock
  . orgSections
  . document
  <$> get
#+END_SRC

#+NAME: Unindent first line of ~ls~
#+BEGIN_SRC haskell
(\s -> case (break isRaw ls) of
        (_, []) -> ls
        (pre, (x:xs)) -> pre ++ (unindent (indent s) x : xs))
  <$> get
#+END_SRC

#+NAME: Imports
#+BEGIN_SRC haskell
import Numeric (showOct)
import qualified System.Directory as D
import qualified System.Environment as Env
import qualified System.FilePath as F
import qualified System.Posix.Files as F
import qualified System.Posix.Types as F
#+END_SRC

#+NAME: stack-packages
#+BEGIN_SRC shell
--package filepath
--package directory
--package unix
#+END_SRC

#+NAME: Tangler
#+BEGIN_SRC haskell
tangleFile :: Options -> Document -> (FilePath, [SourceBlock]) -> IO ()
tangleFile opts _ (fp, []) =
  logM (logLevel opts) Warning $ "* File " ++ fp ++ " seems to be empty."
tangleFile opts doc (fp, bs) = do
  let ls = concatMap
           (\b -> fst $ runState (tangle b) TangleState{ document = doc, indent = [], blocks = Stack [] })
           bs
      ls' = <<Remove redundant line pragmas from ~ls~>>
      contents = concatMap show ls'
      block = head bs
  logM (logLevel opts) Info $ "* Writing file " ++ fp ++ "..."
  if dryRun opts
    then ( logM (logLevel opts) Info "** Dry-run: writing to stdout"
           >> logM (logLevel opts) Info contents
         )
    else do
      let dir = F.takeDirectory fp
      when (mkDir && dir /= ".") $ do
        logM (logLevel opts) Info $ "** Creating missing directories..."
        D.createDirectoryIfMissing True dir
        exists <- F.fileExist fp
        when exists $ do
          logM (logLevel opts) Info $ "** Removing pre-existing file..."
          F.removeLink fp
      logM (logLevel opts) Info $
        "** Writing file contents..."
      writeFile fp contents
      case headerArg ":tangle-mode" block of
        Nothing -> return ()
        Just expr -> do
          let mode = fileMode expr
          logM (logLevel opts) Info $
            "** Setting file mode to #o" ++ showOct mode "..."
          F.setFileMode fp mode
  where
    mkDir = case headerArg ":mkdirp" (head bs) of
              Just (YesNo x) -> x
              _ -> False
#+END_SRC

#+NAME: Remove redundant line pragmas from ~ls~
#+BEGIN_SRC haskell
foldr (\x xs -> let a = (x:xs) in case a of
          (LinePragma _ _ : LinePragma _ _ : _) -> xs
          (LinePragma _ p1 : h : LinePragma _ p2 : xs') ->
            if P.sourceName p1 == P.sourceName p2 && P.sourceLine p1 + 1 == P.sourceLine p2
            then x : h : xs'
            else a
          _ -> a)
      [] ls
#+END_SRC

#+NAME: Tangler
#+BEGIN_SRC haskell
main :: IO ()
main = do
  opts <- O.execParser optParser
  logM (logLevel opts) Debug "* Command line options:"
  logM (logLevel opts) Debug $ PP.render (pretty opts)

  ingested <- fromList <$> ingest (inputFile opts) :: IO OrgFile
  logM (logLevel opts) Debug $ PP.render (pretty ingested)

  let org = fromEither
            $ P.runParser
            (parse :: Parser Document)
            initialOrgState
            (inputFile opts)
            ingested
  logM (logLevel opts) Debug $ PP.render (pretty org)

  home <- Env.getEnv "HOME"
  let fs = <<Gather sections to tangle to files>> :: [(FilePath, [SourceBlock])]
  logM (logLevel opts) Debug $ "files:" ++ show (map fst fs)
  when (showMakeDep opts) $ <<Print tangling makefile dependency line>>

  mapM_ (tangleFile opts org) fs
  where
    optParser = O.info (tanglerOptionParser <**> O.helper)
      ( O.fullDesc
      <> O.progDesc "Tangle the input FILE"
      <> O.header "cctangle - A literate programming tangler" )

#+END_SRC

#+NAME: Gather sections to tangle to files
#+BEGIN_SRC haskell
map (\bs -> (fst (head bs), map snd bs))
  . groupWith fst
  . sortWith fst
  . map (\(fp,b) -> case fp of
            ('~':xs) -> (home ++ xs, b)
            _ -> (fp, b))
  . mapMaybe (\b -> (\fp -> (fp, b)) <$> blockFile b)
  . mapMaybe sectionSourceBlock
  $ orgSections org
#+END_SRC

#+NAME: Print tangling makefile dependency line
#+BEGIN_SRC haskell
putStrLn $ intercalate " " (map fst fs) ++ ": " ++ inputFile opts
#+END_SRC

** Line numbers

#+NAME: Tangler
#+BEGIN_SRC haskell
linePragma :: String -> P.SourcePos -> String
linePragma "haskell" pos =
  unwords ["{-# LINE", show (P.sourceLine pos), "\"" ++ P.sourceName pos ++ "\"", "#-}" ]
linePragma "c" pos =
  unwords ["#line", show (P.sourceLine pos), "\"" ++ P.sourceName pos ++ "\"" ]
linePragma "c++" pos =
  linePragma "c" pos
linePragma _ _ = []
#+END_SRC

* Pretty-Printing

#+NAME: Imports
#+BEGIN_SRC haskell
import qualified Text.PrettyPrint as PP
#+END_SRC

#+NAME: stack-packages
#+BEGIN_SRC shell
--package pretty
#+END_SRC

#+NAME: Pretty printing
#+BEGIN_SRC haskell
class Pretty a where
  pretty :: a -> PP.Doc
  prettyList :: [a] -> PP.Doc
  prettyList = PP.brackets . PP.fcat . PP.punctuate PP.comma . map pretty

instance Pretty PP.Doc where
  pretty = id

instance Pretty Bool where
  pretty True = PP.text "True"
  pretty False = PP.text "False"

instance Pretty Char where
  pretty = PP.char
  prettyList = PP.text

instance Pretty Int where
  pretty = PP.int

instance Pretty a => Pretty (Maybe a) where
  pretty Nothing = PP.text "Nothing"
  pretty (Just a) = pretty a

instance Pretty a => Pretty [a] where
  pretty = prettyList

instance Pretty P.ParseError where
  pretty = PP.text . show
#+END_SRC

#+NAME: Pretty printing
#+BEGIN_SRC haskell
instance (Pretty k, Pretty v) => Pretty (Map.Map k v) where
  pretty = PP.brackets
           . PP.fcat
           . PP.punctuate PP.comma
           . map (\(k,v) -> pretty k PP.<> PP.equals PP.<> pretty v)
           . Map.toList
#+END_SRC

#+NAME: Pretty printing
#+BEGIN_SRC haskell
data PrettyStruct = PrettyStruct String [(String, PP.Doc)]

instance Pretty PrettyStruct where
  pretty (PrettyStruct t ps) =
    let fields = map (\(n,p) -> PP.text n PP.<> PP.colon PP.<+> p) ps
    in PP.text t PP.<> PP.braces (PP.fcat $ PP.punctuate PP.comma fields)
#+END_SRC

#+NAME: Pretty printing
#+BEGIN_SRC haskell
instance Pretty P.SourcePos where
  pretty p = pretty (P.sourceName p)
             PP.<> PP.colon PP.<> pretty (P.sourceLine p)
             PP.<> PP.colon PP.<> pretty (P.sourceColumn p)
#+END_SRC

* Logging

#+NAME: Logging
#+BEGIN_SRC haskell
data LogLevel = Quiet | Error | Warning | Info | Debug deriving Show

instance Pretty LogLevel where
  pretty = PP.text . show

logM :: Pretty a => LogLevel -> LogLevel -> a -> IO ()
logM _ Quiet a = logM' a
logM Quiet _ _ = return ()
logM _ Error a = logM' a
logM Error _ _ = return ()
logM _ Warning a = logM' a
logM Warning _ _ = return ()
logM _ Info a = logM' a
logM Info _ _ = return ()
logM _ Debug a = logM' a

logM' :: Pretty a => a -> IO ()
logM' = putStrLn . PP.render . pretty
#+END_SRC

* Command-Line Options

#+NAME: Imports
#+BEGIN_SRC haskell
import qualified Options.Applicative as O
#+END_SRC

#+NAME: stack-packages
#+BEGIN_SRC shell
--package optparse-applicative
#+END_SRC

#+NAME: Command-line-options
#+BEGIN_SRC haskell
data Options = Options
  { logLevel :: LogLevel
  , dryRun :: Bool
  , showMakeDep :: Bool
  , inputFile :: String
  }

instance Pretty Options where
  pretty o = pretty $ PrettyStruct "Options"
    [ ("log level", pretty $ logLevel o)
    , ("dry-run", pretty $ dryRun o)
    , ("make dependency", pretty $ showMakeDep o)
    , ("input file", pretty $ inputFile o)
    ]

tanglerOptionParser :: O.Parser Options
tanglerOptionParser = Options
  <$> <<Parse log level command line flags>>
  <*> dryRunParser
  <*> O.switch
  ( O.short 'M'
  <> O.long "show-make-dep"
  <> O.help "If given, output a line with a suitable make depencency."
  )
  <*> (<<Parse input file name>>)
#+END_SRC

#+NAME: Parse log level command line flags
#+BEGIN_SRC haskell
((<<=-v= flag parsing>>) <|> (<<=-q= flag parsing>>))
#+END_SRC

#+NAME: =-v= flag parsing
#+BEGIN_SRC haskell
(\vs -> case length vs of
         0 -> Error
         1 -> Warning
         2 -> Info
         _ -> Debug)
<$>
O.some
  ( O.flag' ()
    ( O.short 'v'
      <> O.long "verbose"
      <> O.help "Be verbose. Can be given multiple times for more verbosity."
    ))
#+END_SRC

#+NAME: =-q= flag parsing
#+BEGIN_SRC haskell
O.flag Warning Quiet
  ( O.short 'q'
    <> O.long "quiet"
    <> O.help "Only print things that were asked for."
  )
#+END_SRC

#+NAME: Parse input file name
#+BEGIN_SRC haskell
O.argument O.str
  ( O.metavar "FILE"
  <> O.help "The name of the input file."
  )
#+END_SRC

#+NAME: Command-line-options
#+BEGIN_SRC haskell
dryRunParser :: O.Parser Bool
dryRunParser = O.switch
  ( O.short 'n'
  <> O.long "dry-run"
  <> O.help "If given, do not write any files. Useful when debugging."
  )
#+END_SRC

* Parsing an Org File

I parse Org files with =Parsec=. The reason I chose it over
=Attoparsec= was to be able to have better error messages.

#+NAME: Imports
#+BEGIN_SRC haskell
import qualified Text.Parsec as P
import qualified Text.Parsec.Pos as P
#+END_SRC

#+NAME: stack-packages
#+BEGIN_SRC shell
--package parsec
#+END_SRC

#+NAME: Parser
#+BEGIN_SRC haskell
type Parser = P.Parsec OrgFile OrgState

class Parse a where
  parse :: Parser a
#+END_SRC

#+NAME: Parser
#+BEGIN_SRC haskell
data OrgState = OrgState
  { sectionNumber :: Int
  , propertyStack :: Stack Properties
  }

initialOrgState :: OrgState
initialOrgState = OrgState
  { sectionNumber = 0
  , propertyStack = Stack []
  }
#+END_SRC

#+NAME: Parser
#+BEGIN_SRC haskell
--parserTrace :: Pretty a => a -> Parser ()
--parserTrace l = do
--  (OrgFile ls) <- P.stateInput <$> P.getParserState
--  p <- P.getPosition
--  let label = pretty p PP.<> PP.colon PP.<> pretty l PP.<> PP.colon
--      state = pretty (take 3 ls)
--  Debug.trace (PP.render (PP.hang label 4 state)) $ return ()
#+END_SRC

** Position in the Source

#+NAME: Parser
#+BEGIN_SRC haskell
class Location a where
  newPosition :: P.SourcePos -> Char -> a -> P.SourcePos
#+END_SRC

#+NAME: Parser
#+BEGIN_SRC haskell
instance Location String where
  newPosition pos c _cs = P.updatePosChar pos c
#+END_SRC

** Lines of Input

#+NAME: Parser
#+BEGIN_SRC haskell
data OrgLine = OrgLine P.SourcePos String

instance Location OrgLine where
  newPosition _ _ (OrgLine p _) = p
#+END_SRC

In order to feed ~OrgLine~s into a parser I need to turn them into
~P.Stream~s. While doing that, I force the stream to end with a
newline, be it there to begin with or not. The trick here is to
distinguish between an empty line and a line that just got emptied
after a newline, and I do that by marking the actual end of the line
with the traditional null terminator.

#+NAME: Empty ~OrgLine~
#+BEGIN_SRC haskell
OrgLine _ ('\NUL':_)
#+END_SRC

#+NAME: Parser
#+BEGIN_SRC haskell
instance Monad m => P.Stream OrgLine m Char where
  -- The actual end of the stream
  uncons (<<Empty ~OrgLine~>>) =
    return Nothing
  -- An empty string --- insert last newline
  uncons (OrgLine p []) =
    return $ Just ('\n', OrgLine (P.updatePosChar p '\n') "\NUL")
  -- Uncons a character
  uncons (OrgLine p (x:xs)) =
    return $ Just (x, OrgLine (P.updatePosChar p x) xs)
#+END_SRC

With the above in mind, I filter out =NUL=s when pretty-printing an ~OrgLine~.

#+NAME: Pretty printing
#+BEGIN_SRC haskell
instance Pretty OrgLine where
  pretty (OrgLine p l) =
    pretty p
    PP.<> PP.colon
    PP.<> PP.text (takeWhile (/= '\NUL') l)
#+END_SRC

To deal with streams of ~[OrgLine]~ I have to define a new type,
otherwise there is a conflict with another =Stream= definition.

#+NAME: Parser
#+BEGIN_SRC haskell
newtype OrgFile = OrgFile [OrgLine]
#+END_SRC

In order to be able to obtain valid positions for the end of file, I
make sure to mark the end of the stream based on the ~OrgFile~ having
a single empty string left.

#+NAME: Parser
#+BEGIN_SRC haskell
instance Monad m => P.Stream OrgFile m Char where
  uncons (OrgFile (<<Empty ~OrgLine~>>:[])) = return Nothing
  uncons (OrgFile (x:xs)) = P.uncons x >>= \case
    Nothing -> P.uncons (fromList xs :: OrgFile)
    Just (x',xs') -> return $ Just (x', OrgFile (xs':xs))
  uncons (OrgFile []) =
    error $ "(internal): uncons of empty OrgFile instance"
#+END_SRC

#+NAME: Parser
#+BEGIN_SRC haskell
instance Location OrgFile where
  newPosition pos c (OrgFile (x:_)) =
    newPosition pos c x
  newPosition _ _ (OrgFile []) =
    error $ "(internal): location of empty OrgFile"
#+END_SRC

#+NAME: Parser
#+BEGIN_SRC haskell
instance IsList OrgFile where
  type Item OrgFile = OrgLine
  fromList xs = OrgFile xs
  toList (OrgFile xs) = xs
#+END_SRC

#+NAME: Pretty printing
#+BEGIN_SRC haskell
instance Pretty OrgFile where
  pretty (OrgFile ls) = pretty ls
#+END_SRC

** Basic Parsers

In order to use the positions reported by the streams above, I need to
re-define a few basic =Parsec= parsers. The only meaningful change is
in ~satisfy~.

#+NAME: Parser
#+BEGIN_SRC haskell
satisfy :: (Location s, P.Stream s m Char) => (Char -> Bool) -> P.ParsecT s u m Char
satisfy f = P.tokenPrim
            (\c -> show [c])
            (\pos c cs -> newPosition pos c cs)
            (\c -> if f c then Just c else Nothing)
#+END_SRC

The only parser I /really/ need to re-define is ~endOfLine~, because
it is only when changing lines that positions can switch from one
source file to another in an ~OrgLine~. I do it by replicating the
relevant =Parsec= definitions, substituting my ~satisfy~ in the only
place where it shows up.

#+NAME: Parser
#+BEGIN_SRC haskell
char :: (Location s, P.Stream s m Char) => Char -> P.ParsecT s u m Char
char c = satisfy (==c) P.<?> show [c]

newline :: (Location s, P.Stream s m Char) => P.ParsecT s u m Char
newline = char '\n' P.<?> "lf new-line"

crlf :: (Location s, P.Stream s m Char) => P.ParsecT s u m Char
crlf = char '\r' *> char '\n' P.<?> "crlf new-line"

endOfLine :: (Location s, P.Stream s m Char) => P.ParsecT s u m Char
endOfLine = newline <|> crlf P.<?> "new-line"
#+END_SRC

There is no Org file element that crosses line boundaries, so I also
re-define ~anyChar~ to mean any no-newline character. I also redefine
spaces as meaning any space that is not also a newline character.

#+NAME: Parser
#+BEGIN_SRC haskell
anyChar :: (Location s, P.Stream s m Char) => P.ParsecT s u m Char
anyChar = P.noneOf "\n\r"

space :: P.Stream s m Char => P.ParsecT s u m Char
space = P.satisfy (\c -> isSpace c && notElem c "\n\r")

spaces :: P.Stream s m Char => P.ParsecT s u m String
spaces = P.many space

spaces1 :: P.Stream s m Char => P.ParsecT s u m String
spaces1 = P.many1 space
#+END_SRC

#+NAME: Parser
#+BEGIN_SRC haskell
symbolChar :: P.Stream s m Char => P.ParsecT s u m Char
symbolChar = P.satisfy (\c -> isPrint c && not (isSpace c) && notElem c "()")

symbol :: P.Stream s m Char => P.ParsecT s u m String
symbol = P.many1 symbolChar
#+END_SRC

#+NAME: Parser
#+BEGIN_SRC haskell
line :: Parser a -> Parser a
line p = p <* endOfLine
#+END_SRC

#+NAME: Parser
#+BEGIN_SRC haskell
fromEither :: Pretty a => Either a b -> b
fromEither = either (error . PP.render . pretty) id

ingest :: FilePath -> IO [OrgLine]
ingest fp = do
  ls <- fromEither
       <$> P.parse (P.many1 $ <<Parse a single ~OrgLine~>>) fp
       <$> readFile fp
  foldrM scan [] ls
  where
    scan l@(OrgLine p s) acc =
      case fromEither
           $ P.parse
           (P.setPosition p *> <<Parse an ~#+INCLUDE~ directive>>)
           (P.sourceName p) s
      of
        Nothing -> return (l : acc)
        Just fp' -> (++ acc) <$> ingest fp'
#+END_SRC

#+NAME: Parse a single ~OrgLine~
#+BEGIN_SRC haskell
liftA2 OrgLine P.getPosition (P.manyTill anyChar endOfLine)
#+END_SRC

#+NAME: Parse an ~#+INCLUDE~ directive
#+BEGIN_SRC haskell
P.optionMaybe (
  P.try (P.spaces *> P.string "#+INCLUDE:" *> P.spaces)
  *> P.char '"'
  *> P.manyTill anyChar (P.char '"')
)
#+END_SRC

** Emphasis and Monospace

#+NAME: Pretty printing
#+BEGIN_SRC haskell
instance Pretty TextElement where
  pretty (Bold a) = PP.text "Bold:" PP.<+> pretty a
  pretty (InlineCode a) = PP.text "InlineCode:" PP.<+> pretty a
  pretty (Italics a) = PP.text "Italics:" PP.<+> pretty a
  pretty (Plain a) = pretty a
  pretty (StrikeThrough a) = PP.text "StrikeThrough:" PP.<+> pretty a
  pretty (Verbatim a) = PP.text "Verbatim:" PP.<+> pretty a
#+END_SRC

#+NAME: Parser
#+BEGIN_SRC haskell
instance Parse TextElement where
  parse = literalOr (return . Plain) (<<Parse a marked up text>>)
#+END_SRC

#+NAME: Parse a marked up text
#+BEGIN_SRC haskell
P.try (Bold <$> enclosed '*')
<|> P.try (InlineCode <$> enclosed '~')
<|> P.try (Italics <$> enclosed '/')
<|> P.try (StrikeThrough <$> enclosed '+')
<|> P.try (Verbatim <$> enclosed '=')
#+END_SRC

** Lines of Text

#+NAME: Pretty printing
#+BEGIN_SRC haskell
instance Pretty Text where
  pretty (Text xs) = PP.text "Text:" PP.<+> PP.hcat (map pretty xs)
#+END_SRC

#+NAME: Parser
#+BEGIN_SRC haskell
instance Parse Text where
  parse = do
    --parserTrace "Text: parse"
    Text <$> line (P.many1 parse :: Parser [TextElement])
#+END_SRC

** Lines of Code

#+NAME: Pretty printing
#+BEGIN_SRC haskell
instance Pretty CodeElement where
  pretty (Literal p s) = PP.parens $ pretty p PP.<> PP.colon PP.<> pretty s
  pretty (SectionReference p t) = pretty p PP.<> PP.colon PP.<> PP.char '«' PP.<> pretty t PP.<> PP.char '»'
#+END_SRC

#+NAME: Parser
#+BEGIN_SRC haskell
instance Parse CodeElement where
  parse = literalOr
              (liftA2 Literal P.getPosition . return)
              (P.try $ <<Parse a section reference>>)
#+END_SRC

#+NAME: Parse a section reference
#+BEGIN_SRC haskell
do
  p <- P.try (P.string "<<") *> P.getPosition
  --parserTrace "Trying to parse a code reference after '<<'"
  l <- OrgLine p <$> P.manyTill anyChar (P.try $ P.string ">>")
  let t = fromEither
        $ P.runParser
        (parse :: Parser Text)
        initialOrgState
        (P.sourceName p)
        (fromList [l] :: OrgFile)
      r = SectionReference p t
  --parserTrace $ PP.text "Reference parsed" PP.<> PP.colon PP.<> pretty r
  return r
#+END_SRC

#+NAME: Pretty printing
#+BEGIN_SRC haskell
instance Pretty CodeLine where
  pretty (CodeLine p xs) = pretty p PP.<> PP.colon PP.<> pretty xs
#+END_SRC

#+NAME: Parser
#+BEGIN_SRC haskell
instance Parse CodeLine where
  parse = line (liftA2 CodeLine
                     P.getPosition
                     (P.many parse :: Parser [CodeElement]))
#+END_SRC

** S-Expressions

Org files can contain s-expressions as header property values. I
support a small subset of valid s-expressions, so their type is rather
simple.

#+NAME: Pretty printing
#+BEGIN_SRC haskell
instance Show SExpression where
  show (Atom x) = x
  show (Series xs) = "(" ++ intercalate " " (map show xs) ++ ")"
  show (YesNo x) = show x

instance Pretty SExpression where
  pretty (Atom x) = PP.text x
  pretty (Series xs) = PP.parens $ PP.fsep (map pretty xs)
  pretty (YesNo x) = PP.text (show x)
#+END_SRC

#+NAME: Parser
#+BEGIN_SRC haskell
instance Parse SExpression where
  parse =
    (<<Parse a parenthesized S-expression>>)
    <|>
    P.try (<<Parse a boolean property>>)
    <|>
    (<<Parse an ~Atom~>>)
#+END_SRC

#+NAME: Parse a parenthesized S-expression
#+BEGIN_SRC haskell
Series <$> ( P.try (P.char '(')
             *> spaces
             *> (P.sepEndBy parse spaces1 <* P.char ')')
           )
#+END_SRC

#+NAME: Parse a boolean property
#+BEGIN_SRC haskell
YesNo <$> (
  (P.string "no" *> P.lookAhead P.space *> return False)
  <|>
  (P.string "yes" *> P.lookAhead P.space *> return True)
  )
#+END_SRC

#+NAME: Parse an ~Atom~
#+BEGIN_SRC haskell
Atom <$> (enclosed '"' <|> symbol)
#+END_SRC

I could not avoid evaluating some expressions, namely those used to
conditionally tangle things depending on the system type. Those are of
the form

#+BEGIN_SRC emacs-lisp :tangle no
(when (eq system-type 'gnu/linux) "~/file/name")
#+END_SRC

Valid =system-type= values include =gnu/linux=, =darwin=, and =windows-nt=.

#+NAME: Parser
#+BEGIN_SRC haskell
class Eval a where
  eval :: a -> a

instance Eval SExpression where
  eval (Series [Atom "eq", Atom "system-type", Atom ('\'':t)]) =
    YesNo $ case (Sys.os, t) of
              ("linux", "gnu/linux") -> True
              ("mingw32", "windows-nt") -> True
              ("darwin", "darwin") -> True
              _ -> False

  eval (Series [Atom "unless", expr, result]) =
    case eval expr of
      YesNo False -> eval result
      YesNo True  -> YesNo False
      expr' -> expr'

  eval (Series [Atom "when", expr, result]) =
    case eval expr of
      YesNo True -> eval result
      expr' -> expr'

  eval x = x
#+END_SRC

#+NAME: Imports
#+BEGIN_SRC haskell
import qualified System.Info as Sys
#+END_SRC

** Properties

Org properties are key-value pairs assigned to a property name.

#+NAME: Parser
#+BEGIN_SRC haskell
instance Eval Property where; eval = Map.map eval
instance Eval Properties where; eval = Map.map eval
#+END_SRC

#+NAME: Parser
#+BEGIN_SRC haskell
class HeaderArgs a where
  headerArgs :: a -> Property
  headerArg :: String -> a -> Maybe SExpression
  headerArg k a = Map.lookup k $ headerArgs a

instance HeaderArgs Properties where
  headerArgs = Map.findWithDefault Map.empty "header-args"
#+END_SRC

#+NAME: Parser
#+BEGIN_SRC haskell
instance Parse Properties where
  parse = (<<Parse a =#+PROPERTY= line>>)
              <|> (<<Parse a =:PROPERTIES:= drawer>>)
#+END_SRC

#+NAME: Parse a =#+PROPERTY= line
#+BEGIN_SRC haskell
do
  _ <- P.try (P.string "#+PROPERTY:") *> spaces
  p <- symbol <* spaces1
  kvs <- <<Parse a line of property key-value pairs>>
  return $ Map.singleton p kvs
#+END_SRC

#+NAME: Parse a line of property key-value pairs
#+BEGIN_SRC haskell
line (Map.fromList
      <$> P.sepEndBy
       (<<Parse a single key-value property pair>>)
       spaces1)
#+END_SRC

#+NAME: Parse a single key-value property pair
#+BEGIN_SRC haskell
do
  k <- symbol <* spaces1
  v <- parse :: Parser SExpression
  return (k, v)
#+END_SRC

#+NAME: Parse a =:PROPERTIES:= drawer
#+BEGIN_SRC haskell
do
  _ <- P.try (spaces *> P.string ":PROPERTIES:" *> spaces *> endOfLine)
  Map.fromList <$> P.manyTill
    (<<Parse a =:PROPERTIES:= drawer line>>)
    (P.try (spaces *> P.string ":END:" *> spaces *> endOfLine))
#+END_SRC

#+NAME: Parse a =:PROPERTIES:= drawer line
#+BEGIN_SRC haskell
do
  p <- spaces *> (enclosed ':' <* spaces)
  kvs <- <<Parse a line of property key-value pairs>>
  return (p, kvs)
#+END_SRC

#+NAME: Parser
#+BEGIN_SRC haskell
fileMode :: SExpression -> F.FileMode
fileMode (Series (Atom "identity" : Atom ('#':'o':a:g:u:[]) : [])) =
  fromIntegral $ 8 * ((8 * oct a) + oct g) + oct u
  where oct c = ord c - ord '0'
fileMode _ = 420
#+END_SRC

** Headlines

#+NAME: Pretty printing
#+BEGIN_SRC haskell
instance Pretty Headline where
  pretty (Headline l t) =
    PP.text "Headline"
    PP.<> PP.braces (pretty l)
    PP.<+> pretty t
#+END_SRC

#+NAME: Parser
#+BEGIN_SRC haskell
instance Parse Headline where
  parse = do
    s <- P.try (char '*') *> P.many (char '*')
    _ <- spaces1
    t <- parse :: Parser Text
    return $ Headline (length s) t
#+END_SRC

#+NAME: Parser
#+BEGIN_SRC haskell
headlineLevel :: Headline -> Int
headlineLevel (Headline x _) = x
#+END_SRC

** Code Blocks

#+NAME: Parser
#+BEGIN_SRC haskell
#+END_SRC

#+NAME: Pretty printing
#+BEGIN_SRC haskell
instance Pretty SourceBlock where
  pretty s = pretty $ PrettyStruct "SourceBlock"
               [ ("name", pretty (blockName s))
               , ("language", pretty (blockLanguage s))
               , ("properties", pretty (blockProperties s))
               , ("derived properties", pretty (blockDerivedProperties s))
               , ("location", pretty (blockLocation s))
               , ("lines", pretty (blockLines s))
               ]
#+END_SRC

#+NAME: Parser
#+BEGIN_SRC haskell
instance HeaderArgs SourceBlock where
  headerArgs = blockDerivedProperties
#+END_SRC

#+NAME: Parser
#+BEGIN_SRC haskell
instance Parse SourceBlock where
  parse = do
    --parserTrace "SourceBlock: trying to find a code block here"
    n  <- P.optionMaybe (<<Parse a =#+NAME= line>>)
    i  <- P.try (spaces <* (P.string "#+BEGIN_SRC" *> spaces1))
    --parserTrace "SourceBlock: found a code block, parsing language"
    l  <- symbol <* spaces
    --parserTrace "SourceBlock: found a code block, parsing properties"
    ps <- <<Parse a line of property key-value pairs>>
    ps' <- Map.union ps . headerArgs . top . propertyStack <$> P.getState
    p  <- P.getPosition
    --parserTrace "SourceBlock: found a code block, parsing lines"
    ls <- P.manyTill (P.string i *> parse :: Parser CodeLine)
         (P.try (line (P.string i *> P.string "#+END_SRC" *> spaces)))
    --parserTrace "SourceBlock: code block parsed"
    return $ SourceBlock
      { blockName = n
      , blockLanguage = l
      , blockProperties = ps
      , blockDerivedProperties = eval ps'
      , blockLocation = p
      , blockLines = ls
      }
#+END_SRC

#+NAME: Parse a =#+NAME= line
#+BEGIN_SRC haskell
P.try (spaces *> P.string "#+NAME:")
*> spaces
*> parse :: Parser Text
#+END_SRC

#+NAME: Parser
#+BEGIN_SRC haskell
blockFile :: SourceBlock -> Maybe FilePath
blockFile SourceBlock{ blockName = Just _ } = Nothing
blockFile b =
  case headerArg ":tangle" b of
    Nothing -> Nothing
    Just (Atom f) -> Just f
    _ -> Nothing
#+END_SRC

** Utility parsers

The =Parsec= library provides a ~spaces~ function, but that also skips
newlines. The parsers below implement the behaviors I need.

#+NAME: Parser
#+BEGIN_SRC haskell
emptyLine :: (Location s, P.Stream s m Char) => P.ParsecT s u m ()
emptyLine = void $ spaces *> endOfLine

skipEmptyLines :: (Location s, P.Stream s m Char) => P.ParsecT s u m ()
skipEmptyLines = P.skipMany (P.try emptyLine)
#+END_SRC

#+NAME: Parser
#+BEGIN_SRC haskell
literalOr :: (Location s, P.Stream s m Char) => (String -> P.ParsecT s u m a) -> P.ParsecT s u m a -> P.ParsecT s u m a
literalOr f p = scan "" where
  scan [] = p <|> (anyChar >>= scan . (:""))
  scan acc =
    ((P.lookAhead p) *> (f $ reverse acc))
    <|> (anyChar >>= scan . (:acc))
    <|> (f $ reverse acc)
#+END_SRC

I will need to parse strings enclosed by a single character delimiter
multiple times. This is very similar to ~between~, but I don't allow
the contents to span multiple lines.

#+NAME: Parser
#+BEGIN_SRC haskell
enclosed :: (Location s, P.Stream s m Char) => Char -> P.ParsecT s u m String
enclosed d = P.try (P.char d) *> P.manyTill anyChar (P.char d)
#+END_SRC

** Sections

#+NAME: Pretty printing
#+BEGIN_SRC haskell
instance Pretty Section where
  pretty s = pretty $ PrettyStruct "Section"
               [ ("headline", pretty (sectionHeadline s))
               , ("properties", pretty (sectionProps s))
               , ("derived properties", pretty (sectionDerivedProperties s))
               , ("text", pretty (sectionDocumentation s))
               , ("code", pretty (sectionSourceBlock s))
               ]
#+END_SRC

#+NAME: Parser
#+BEGIN_SRC haskell
instance HeaderArgs Section where
  headerArgs = headerArgs . sectionDerivedProperties
#+END_SRC

#+NAME: Parser
#+BEGIN_SRC haskell
instance Parse Section where
  parse = do
    skipEmptyLines
    h <- P.optionMaybe parse :: Parser (Maybe Headline)
    --parserTrace $ PP.text "Section: headline=" PP.<> pretty h
    skipEmptyLines
    ps <- parse <|> return Map.empty :: Parser Properties
    --parserTrace $ PP.text "Section: properties=" PP.<> pretty ps
    when (isJust h) $ do
      P.updateState (\s ->
        s{ propertyStack =
             push (Map.union ps $ top $ propertyStack s)
             . resize (headlineLevel $ fromJust h)
             $ propertyStack s
         })
    P.updateState (\s -> s{ sectionNumber = 1 + (sectionNumber s) })
    ps' <- top . propertyStack <$> P.getState
    --parserTrace $ PP.text "Section: derived properties=" PP.<> pretty ps'
    skipEmptyLines
    --parserTrace "Section: about to scan for text and code"
    (ts, c) <- scan
    --parserTrace "Section: section parsed"
    return Section
      { sectionHeadline = h
      , sectionProps = ps
      , sectionDerivedProperties = eval ps'
      , sectionDocumentation = ts
      , sectionSourceBlock = c
      }
      where
        scan :: Parser ([Text], Maybe SourceBlock)
        scan = <<Parse section documentation followed by a code block>>
#+END_SRC

#+NAME: Parse section documentation followed by a code block
#+BEGIN_SRC haskell
do{ c <- parse :: Parser SourceBlock; return ([], Just c) }
<|>
  (do
      P.skipMany1 (P.try emptyLine)
      c <- P.optionMaybe parse :: Parser (Maybe SourceBlock)
      return ([], c)
  )
<|>
  (do
      t <- parse :: Parser Text
      s <- scan
      return ( t:(fst s), snd s )
  )
#+END_SRC

** Keywords

#+NAME: Parser
#+BEGIN_SRC haskell
instance Pretty Keyword where
  pretty (AuthorKeyword a) = PP.text "Author:" PP.<+> pretty a
  pretty (PropertyKeyword a) = PP.text "Property:" PP.<+> pretty a
  pretty (TitleKeyword a) = PP.text "Title:" PP.<+> pretty a
  pretty (OtherKeyword a) = PP.text "Other:" PP.<+> pretty a
#+END_SRC

#+NAME: Parser
#+BEGIN_SRC haskell
instance Parse Keyword where
  parse = propertyKeyword <|> titleKeyword <|> authorKeyword <|> otherKeyword
    where
      authorKeyword = do
        keywordStart "#+AUTHOR:"
        AuthorKeyword <$> parse
      propertyKeyword = do
        PropertyKeyword <$> <<Parse a =#+PROPERTY= line>>
      titleKeyword = do
        keywordStart "#+TITLE:"
        TitleKeyword <$> parse
      otherKeyword = do
        _ <- P.try $ P.string "#+"
        t <- P.many anyChar
        _ <- endOfLine
        return $ OtherKeyword t
      keywordStart h = void $ P.try (P.string h *> spaces)
#+END_SRC

#+NAME: Parser
#+BEGIN_SRC haskell
headerProperties :: [Keyword] -> Properties
headerProperties = foldl acc mempty where
    acc a (PropertyKeyword p) = Map.union p a
    acc a _ = a
#+END_SRC

** Document

#+NAME: Pretty printing
#+BEGIN_SRC haskell
instance Pretty Document where
  pretty d = pretty $ PrettyStruct "Document"
               [ ("keywords", pretty (orgKeywords d))
               , ("sections", pretty (orgSections d))
               ]
#+END_SRC

#+NAME: Parser
#+BEGIN_SRC haskell
instance Parse Document where
  parse = do
    --parserTrace "Document: Parsing keywords"
    hs <- P.many parse :: Parser [Keyword]
    P.updateState $ \s -> s{ propertyStack = Stack [headerProperties hs] }
    skipEmptyLines
    --parserTrace "Document: Parsing sections"
    ss <- P.many parse :: Parser [Section]
    skipEmptyLines *> P.eof
    return Document
      { orgKeywords = hs
      , orgSections = ss
      }
#+END_SRC

* Weaving

#+BEGIN_SRC haskell :tangle "bin/ccweave.hs" :tangle-mode (identity #o444)
<<Common-ccweb-code>>

main :: IO ()
main = do
  opts <- O.execParser optParser
  logM (logLevel opts) Debug "* Command line options:"
  logM (logLevel opts) Debug (PP.render (pretty opts))
  --let doc = parseDocument state (inputFile opts)
  --logM (logLevel opts) Debug $ PP.render (pretty doc)
  --putStrLn (weave doc)
  where
    optParser = O.info (tanglerOptionParser <**> O.helper)
      ( O.fullDesc
      <> O.progDesc "Weave the input FILE"
      <> O.header "ccweave - A literate programming weaver" )

<<Weaver>>
#+END_SRC

#+NAME: Weaver
#+BEGIN_SRC haskell
--class Weave a where
--  weave :: a -> String
#+END_SRC

#+NAME: Weaver
#+BEGIN_SRC haskell
--instance Weave Char where
--  weave '&' = "{\\AM}"
--  weave '\\' = "{\\BS}"
--  weave '{' = "{\\LB}"
--  weave '}' = "{\\RB}"
--  weave '~' = "{\\TL}"
--  weave '_' = "{\\UL}"
--  weave '^' = "{\\CF}"
--  weave '#' = "{\\#}"
--  weave '$' = "{\\$}"
--  weave '%' = "{\\%}"
--  weave c = [c]
#+END_SRC

#+NAME: Weaver
#+BEGIN_SRC haskell
--instance Weave TextElement where
--  weave (Plain s) = s
--  weave (Bold s) = concat ["{\\bf ", s, "}"]
--  weave (Italics s) = concat ["{\\it ", s, "\\/}"]
--  weave (InlineCode s) = "\\hbox{\\tenex " ++ concatMap weave s ++ "}"
--  weave (Verbatim s) = "\\hbox{\\tenex " ++ concatMap weave s ++ "}"
#+END_SRC

#+NAME: Weaver
#+BEGIN_SRC haskell
--instance Weave Text where
--  weave (Text ts) = concatMap weave ts
#+END_SRC

The =\fi= at the end is necessary to balance out conditionals opened
by the =cwebmac= macros issued at every section.

#+NAME: Weaver
#+BEGIN_SRC haskell
--instance Weave Section where
--  weave s = unlines (header : text) ++ code ++ "\\fi\n"
--    where
--      text = map weave (sectionText s)
--      header = concat $
--        case groupHeader s of
--          Nothing -> [ "\\M{", show (sectionNumber s), "}"]
--          Just h ->
--            [ "\\N{", show (sectionDepth h), "}"
--            , "{", show (sectionNumber s), "}"
--            , weave (sectionHeaderTitle h), "."
--            ]
--      code = concat $
--        case sectionCode s of
--          Nothing -> []
--          Just _ -> [ "\\X", ":", "\\X", "${}", "\\equiv{}$\n" ]
#+END_SRC

#+NAME: Weaver
#+BEGIN_SRC haskell
--instance Weave Document where
--  weave Document{documentHeaders = []} = ""
--  weave doc@Document{documentHeaders = _} =
--    unlines [ "\\input cwebmac"
--            , concatMap weave (documentSections doc)
--            , "\\inx"
--            , "\\fin"
--            , "\\con"
--            ]
#+END_SRC

** Cross-referencing code blocks

Whenever I am printing a code block, I need to know which other blocks
use it, and what other blocks have the same name.

* Building

One interesting application of a multi-file literate programming tool
is that not only I can generate the source files, but I can also
generate the /build system/ itself.

#+BEGIN_SRC makefile :tangle "GNUmakefile" :tangle-mode (identity #o644)
all: bin/cctangle bin/ccweave
test: test_cctangle

<<=GNUmakefile= rules>>
#+END_SRC

The rule below is the one I use most often: I have a terminal open
with =make inotify= running. This makes the compilation and tests run
every time I change this source file.

#+NAME: =GNUmakefile= rules
#+BEGIN_SRC makefile
inotify:
	while inotifywait -e modify ccweb.org; do \
	make test; \
	done
#+END_SRC

Next, I deal with bootstrapping: In order to tangle this file, I need
a tangler. In theory there is one everybody can install -- Emacs
itself. But that is a heavy burden on users. An easier way is to use
the Haskell tool stack and have the bootstrapping executables be the
source code, with a =stack script= preamble.

The =bootstrap= target compiles everything (with the previous
bootstrapper), runs the tests, and, if everything looks fine, builds
the new bootstrapper from the new sources.

#+NAME: =GNUmakefile= rules
#+BEGIN_SRC makefile
define STACK_PREAMBLE
#!/usr/bin/env stack
<<Stack-preamble>>
endef

export STACK_PREAMBLE

BOOTSTRAP_TANGLER := bootstrap/cctangle

bootstrap: ${BOOTSTRAP_TANGLER}

bootstrap/%: bin/%.hs test_%
	@mkdir -p bootstrap
	@rm -f $@
	@echo "$$STACK_PREAMBLE" > $@
	@cat $< >> $@
	@chmod 555 $@
#+END_SRC

The bootstrapper is used to generate all the files, which are
themselves listed by the bootstrapper.

#+NAME: =GNUmakefile= rules
#+BEGIN_SRC makefile
FILES := $(shell bootstrap/cctangle -Mnq ccweb.org | cut -f1 -d:)

clean:
	rm -f $(filter-out GNUmakefile,${FILES})

${FILES}: ccweb.org
	@mkdir -p bin
	@rm -f $@
	${BOOTSTRAP_TANGLER} $<
#+END_SRC

#+NAME: =GNUmakefile= rules
#+BEGIN_SRC makefile
bin/%: bin/%.hs
	@rm -f $@
	stack build --trace $(subst bin/,ccweb:,$@)
	cp `stack exec -- which $(subst bin/,,$@)` $@
#+END_SRC

#+NAME: =GNUmakefile= rules
#+BEGIN_SRC makefile
DIFF := git --no-pager diff --no-index

test_cctangle: bin/cctangle
	@rm -f tests/out/tangle*
	stack exec cctangle -- -nvvvv tests/tangle.org >/dev/null
	stack exec cctangle -- -Mnvvvv tests/tangle.org >/dev/null
	stack exec cctangle -- -Mnvvvv ccweb.org >/dev/null
	stack exec cctangle -- tests/tangle.org >/dev/null
	${DIFF} tests/ref/tangle001.hs tests/out/tangle001.hs
	${DIFF} tests/ref/tangle002.hs tests/out/tangle002.hs
	${DIFF} tests/ref/tangle003.hs tests/out/tangle003.hs
	${DIFF} tests/ref/tangle004.hs tests/out/tangle004.hs
	${DIFF} tests/ref/tangle005.hs tests/out/tangle005.hs
	@rm -f tests/out/tangle*

test_ccweave: bin/ccweave
	@rm -f tests/ref/weave*
	stack exec ccweave -- tests/weave001.org
#+END_SRC

#+BEGIN_SRC yaml :tangle "stack.yaml" :tangle-mode (identity #o644)
resolver: lts-12.22

packages:
  - '.'
#+END_SRC

#+BEGIN_SRC yaml :tangle "ccweb.cabal" :tangle-mode (identity #o644)
name: ccweb
version: 1.0.0.0
build-type: Simple
cabal-version: >=1.10

executable cctangle
  main-is: bin/cctangle.hs
  build-depends:
                base, containers, directory, filepath, mtl,
                optparse-applicative, parsec, pretty, unix
  default-language: Haskell2010
  ghc-options: -Wall -Werror -O2 -rtsopts
  hs-source-dirs: .
  other-modules:

executable ccweave
  main-is: bin/ccweave.hs
  build-depends:
                base, containers, directory, filepath, mtl,
                optparse-applicative, parsec, pretty, unix
  default-language: Haskell2010
  ghc-options: -Wall -O2 -rtsopts
  hs-source-dirs: .
  other-modules:
#+END_SRC
