* Building

One interesting application of a multi-file literate programming tool
is that not only I can generate the source files, but I can also
generate the /build system/ itself.

#+BEGIN_SRC makefile :tangle "GNUmakefile" :tangle-mode (identity #o644)
all: bin/cctangle bin/ccweave
test: test_cctangle test_ccweave

<<=GNUmakefile= rules>>
#+END_SRC

The simplest rule is =clean=:

#+NAME: =GNUmakefile= rules
#+BEGIN_SRC makefile
clean:
	git clean -x -f
#+END_SRC

The rule below is the one I use most often: I have a terminal open
with =make inotify= running. This makes the compilation and tests run
every time I change one of the source files.

#+NAME: =GNUmakefile= rules
#+BEGIN_SRC makefile
inotify:
	while inotifywait -e modify $$(bootstrap/cctangle -Inq ccweb.org) tests/*.org; do \
	make -j test; \
	done
#+END_SRC

Next, I deal with bootstrapping: In order to tangle this file, I need
a tangler. In theory there is one everybody can install -- Emacs
itself. But that is a heavy burden on users, and this repository
contains the source of a working tangler. Bootstraping then boils down
to compiling the tangler and copying it over to the =bootstrap=
directory.

#+NAME: =GNUmakefile= rules
#+BEGIN_SRC makefile
bootstrap:
	@mkdir -p bootstrap
	@rm -f bootstrap/cctangle
	stack install ccweb --local-bin-path $@

.PHONY: bootstrap
#+END_SRC

Another interesting characeteristic of systems like this is that one
does not know in advance which files are being generated. The trick is
here is to use the tangler itself to tell me what is going to be generated
(with the =-O= flag), store that into a makefile variable, and then
read it in.

#+NAME: =GNUmakefile= rules
#+BEGIN_SRC makefile
TANGLED_FILES :=
-include ccweb.outs

ccweb.outs:
	@rm -f $@
	test -x bootstrap/cctangle && (bootstrap/cctangle -Onq ccweb.org | sed -e 's/^/TANGLED_FILES += /' > $@)
#+END_SRC

These output files, of course, depend not only on =ccweb.org=, but
also on any files it includes. The way do deal with this is rather
standard: I include a dependency file that is generated by the
``compiler'' (the tangler) itself.

#+NAME: =GNUmakefile= rules
#+BEGIN_SRC makefile
-include ccweb.deps

ccweb.deps:
	@rm -f $@
	test -x bootstrap/cctangle && (bootstrap/cctangle -Mnq ccweb.org | sed -e 's/^/ccweb.outs ccweb.deps /' > $@)
#+END_SRC

Once the output files and what they depend on are identified, I can
generate them with a dependency-less rule.

#+NAME: =GNUmakefile= rules
#+BEGIN_SRC makefile
${TANGLED_FILES}:
	@mkdir -p $(dir $@)
	@rm -f $@
	bootstrap/cctangle ccweb.org
#+END_SRC

Two of those tangled files are the Haskell sources for =cctangle= and
=ccweave=. They must be compiled in a single rule, because =stack=
does not like to be called in parallel.

#+NAME: =GNUmakefile= rules
#+BEGIN_SRC makefile
bin/%tangle bin/%weave: bin/cctangle.hs bin/ccweave.hs
	@rm -f $@
	stack build -j2 --trace
	stack install ccweb --local-bin-path bin
#+END_SRC

Testing is done by generating files and comparing them to
references. To make those differences visually pleasing, I use =git=
to display them.

#+NAME: =GNUmakefile= rules
#+BEGIN_SRC makefile
DIFF := git --no-pager diff --no-index
#+END_SRC

#+NAME: =GNUmakefile= rules
#+BEGIN_SRC makefile
test_cctangle: bin/cctangle
	@rm -f tests/out/tangle*
	stack exec cctangle -- -n tests/tangle.org >/dev/null
	stack exec cctangle -- -IOn tests/tangle.org >/dev/null
	stack exec cctangle -- -IOn ccweb.org >/dev/null
	stack exec cctangle -- tests/tangle.org >/dev/null
	for out in $(shell stack exec cctangle -- -Oq tests/tangle.org); do \
		echo "$$out..." && ${DIFF} $${out/out/ref} $$out ; \
	done
	@rm -f tests/out/tangle*

test_ccweave: bin/ccweave
	@rm -f tests/ref/weave*
	stack exec ccweave -- tests/weave001.org
#+END_SRC

#+BEGIN_SRC yaml :tangle "stack.yaml" :tangle-mode (identity #o644)
resolver: lts-12.22

packages:
  - '.'
#+END_SRC

#+BEGIN_SRC yaml :tangle "ccweb.cabal" :tangle-mode (identity #o644)
name: ccweb
version: 2.0
build-type: Simple
cabal-version: >=1.10

executable cctangle
  main-is: bin/cctangle.hs
  build-depends:
                ansi-terminal, base, containers, directory, filepath, hostname,
                mtl, optparse-applicative, parsec, pretty, unix
  default-language: Haskell2010
  ghc-options: -Wall -Werror -O2 -rtsopts
  hs-source-dirs: .
  other-modules: Paths_ccweb

executable ccweave
  main-is: bin/ccweave.hs
  build-depends:
                ansi-terminal, base, containers, directory, filepath, hostname,
                mtl, optparse-applicative, parsec, pretty, unix
  default-language: Haskell2010
  ghc-options: -Wall -O2 -rtsopts
  hs-source-dirs: .
  other-modules: Paths_ccweb
#+END_SRC
