* Parsing

We will do some extra work during parsing to avoid multiple passes
over the structure, and in order to do that we will keep some
state. This state will contain the evaluation context (used when
evaluating s-expressions), the log level specified by the user, a
property stack, and the current section number.

#+NAME: Parser
#+BEGIN_SRC haskell
data ParserState = ParserState
  { sectionCounter :: Int
  , propertyStack  :: Stack Properties
  , evalContext    :: Map.Map SExpr SExpr
  , parserLogLevel :: LogLevel
  }
#+END_SRC

As with other things, we pretty-print it as a map.

#+NAME: Pretty printing
#+BEGIN_SRC haskell
instance Pretty ParserState where
  pretty = prettyStruct "ParserState"
    [ ("counter", pretty . sectionCounter)
    , ("eval context", pretty . evalContext)
    , ("log level", pretty . parserLogLevel)
    , ("property stack", pretty . propertyStack)
    ]
#+END_SRC

Based on this state, we define the main parser type, and a type class
to be instantiated by all things that know how to parse
themselves. The stream type is that of ~OrgLines~, which we will deal
with in the next section.

#+NAME: Parser
#+BEGIN_SRC haskell
type Parser = P.Parsec OrgLines ParserState

class Parse a where
  parse :: Parser a
#+END_SRC

** Lines of Input

Before parsing an Org file into a ~Document~, we will read its
contents as lines, expanding all the =#+INCLUDE= directives while at
it. The end result will be a list of lines where each line will
contain not only the contents of that line, but also the name of the
file it came from, and the line number in that file. This will be
important when inserting line pragmas while tangling.

#+NAME: Parser
#+BEGIN_SRC haskell
data OrgLine = OrgLine P.SourcePos String
#+END_SRC

We have to remove the trailing newline when pretty-printing, as the
decision to break a line or not is up to the pretty-printing algorithm.

#+NAME: Pretty printing
#+BEGIN_SRC haskell
instance Pretty OrgLine where
  pretty (OrgLine p l) =
    PP.hcat [pretty p, PP.colon, PP.text (takeWhile (/= '\n') l), PP.char '␤']
#+END_SRC

Now to ingesting those lines. The parser we are going to use for both
ingesting and final parsing is =Parsec=.

#+NAME: Imports
#+BEGIN_SRC haskell
import qualified Text.Parsec as P
import qualified Text.Parsec.Pos as P
#+END_SRC

The Stack package for the boostrapper is =parsec=.

#+NAME: stack-packages
#+BEGIN_SRC shell
--package parsec
#+END_SRC

Ingesting a file is a matter of reading all of its lines, then recursively
replacing any =#+INCLUDE= directives by the files they
reference. Reading a file's lines can be done with the prelude's
~readFile~ and ~lines~ functions, but I then have to put back the lost
newlines to facilitate things later on.

#+NAME: Parser
#+BEGIN_SRC haskell
ingest :: FilePath -> IO [OrgLine]
ingest file = do
    zipWith OrgLine [P.newPos file l 1 | l <- [1..]] . map (++"\n") . lines
      <$> readFile file
      >>= foldrM scan []
  where
    scan l@(OrgLine pos s) ls =
      maybe (return (l : ls)) (fmap (++ ls) . ingest)
      $ (<<Parse an ~#+INCLUDE~ directive>> :: String -> Maybe FilePath) s
#+END_SRC

I invoke a parser to check whether the line is an =#+INCLUDE= line or
not, taking the precaution to set the position of the string to parse
to the correct position in the input file, so that errors are
properly reported.

#+NAME: Parse an ~#+INCLUDE~ directive
#+BEGIN_SRC haskell
fromEither . P.parse
(P.setPosition pos *>
    P.optionMaybe (
      P.try (P.spaces *> P.string "#+INCLUDE:" *> P.spaces)
      *> P.char '"'
      *> P.manyTill anyChar (P.char '"')
    ))
(P.sourceName pos)
#+END_SRC

The ~fromEither~ function above returns a successful result, or errors out
by pretty-printing the error. I will use it a handful of times more later.

#+NAME: Common =CCWEB= code
#+BEGIN_SRC haskell
fromEither :: Pretty a => Either a b -> b
fromEither = either (error . PP.render . pretty) id
#+END_SRC

I also used an ~anyChar~ parser above. It is similar to the one
defined by =Parsec=, except it does not cross line boundaries.

#+NAME: Parser
#+BEGIN_SRC haskell
anyChar :: (P.Stream s m Char) => P.ParsecT s u m Char
anyChar = P.noneOf "\n\r"
#+END_SRC

Now that I have an Org file ingested into a list of ~OrgLine~, I
need to make those available for the next parser as a ~P.Stream~.

#+NAME: Parser
#+BEGIN_SRC haskell
instance Monad m => P.Stream OrgLine m Char where
  uncons (OrgLine _ []) =
    return Nothing
  uncons (OrgLine p (x:xs)) =
    return $ Just (x, OrgLine (P.updatePosChar p x) xs)
#+END_SRC

The other piece of the ~P.Stream~ puzzle is to support lists of
~OrgLine~. I can't simply declare ~[OrgLine]~ an instance of ~Stream~
because that would conflict with then instance =Parsec= declares for
tokens. I get around it by wrapping the list in a new type.

#+NAME: Parser
#+BEGIN_SRC haskell
newtype OrgLines = OrgLines [OrgLine]
#+END_SRC

Pretty-printing this is rather trivial.

#+NAME: Pretty printing
#+BEGIN_SRC haskell
instance Pretty OrgLines where
  pretty (OrgLines ls) = pretty ls
#+END_SRC

This is now turned into a ~Stream~. In order to be able to obtain
valid positions for the end of file, I make sure to mark the end of
the stream based on the ~OrgLines~ having a single empty string left.

#+NAME: Parser
#+BEGIN_SRC haskell
instance Monad m => P.Stream OrgLines m Char where
  uncons (OrgLines (x:[])) = P.uncons x >>= \case
    Nothing -> return Nothing
    Just (x',xs') -> return $ Just (x', OrgLines (xs':[]))
  uncons (OrgLines (x:xs)) = P.uncons x >>= \case
    Nothing -> P.uncons (fromList xs :: OrgLines)
    Just (x',OrgLine _ []) -> return $ Just (x', OrgLines xs)
    Just (x',xs') -> return $ Just (x', OrgLines (xs':xs))
  uncons (OrgLines []) =
    error $ "(internal): uncons of empty OrgLines instance"
#+END_SRC

** Basic Parsers

When I talk about whitespace, I will be talking about
/horizontal whitespace/. The =Parsec= parsers don't have those, so I
implement them below.

#+NAME: Parser
#+BEGIN_SRC haskell
space :: Parser Char
space = P.satisfy (\c -> isSpace c && notElem c "\n\r")

spaces :: Parser String
spaces = P.many space

spaces1 :: Parser String
spaces1 = P.many1 space
#+END_SRC

There will be a few places where I will need to parse a /symbol/,
which I fuzzily consider to be a ``variable name.'' The ~=~
character, for example, is a valid Lisp symbol name, but not a valid
Org property name.

#+NAME: Parser
#+BEGIN_SRC haskell
symbolChar :: Parser Char
symbolChar = P.satisfy (\c -> isPrint c && not (isSpace c) && notElem c "()=")

symbol :: Parser String
symbol = P.many1 symbolChar
#+END_SRC

In order to make use of the positions reported by an ~OrgLines~
stream, I need to re-define a few basic =Parsec= parsers. The only
meaningful change is in ~satisfy~. The standard implementation updates
the position according to the character just consumed, meaning the
parser always ``thinks'' it is in the same file. My implementation
will use the location stored in the current ~OrgLine~, each of which
may come from a different file.

#+NAME: Parser
#+BEGIN_SRC haskell
satisfy :: (Char -> Bool) -> Parser Char
satisfy f = P.tokenPrim
            (\c -> show [c])
            (\pos _ (OrgLines rest) ->
               case rest of
                 (OrgLine pos' _):_ -> pos'
                 [] -> error $ show pos ++ ": (internal) empty OrgLines")
            (\c -> if f c then Just c else Nothing)
#+END_SRC

The only parser I /really/ need to re-define for positioning purposes
is ~endOfLine~, because it is only when changing lines that positions
can switch from one source file to another in an ~OrgLine~. I will do
it by replicating the relevant =Parsec= definitions, substituting our
~satisfy~ in the only place where it shows up.

#+NAME: Parser
#+BEGIN_SRC haskell
char :: Char -> Parser Char
char c = satisfy (==c) P.<?> show [c]

newline :: Parser Char
newline = char '\n' P.<?> "lf new-line"

crlf :: Parser Char
crlf = char '\r' *> char '\n' P.<?> "crlf new-line"

endOfLine :: Parser Char
endOfLine = newline <|> crlf P.<?> "new-line"
#+END_SRC

There are places where I need to check whether or not the parser is
positioned at the start of a line. This is more complicated, because
it is not indicated by the character I am looking at, but at the
/position/ of the character.

#+NAME: Parser
#+BEGIN_SRC haskell
beginningOfLine :: Parser ()
beginningOfLine = do
  c <- P.sourceColumn <$> P.getPosition
  succeedWhen (c == 1)
#+END_SRC

The ~succeedWhen~ parser used above, and the corresponding ~failWhen~,
are trivially implemented in terms of ~satisfy~.

#+NAME: Parser
#+BEGIN_SRC haskell
succeedWhen :: Bool -> Parser ()
succeedWhen True = return ()
succeedWhen False = void $ satisfy (\_ -> False)

failWhen :: Bool -> Parser ()
failWhen = succeedWhen . not
#+END_SRC

** Parser Combinators

The ~manyTill~ parser parses something until something else
appears, then returns the list of things parsed. The only difference
between ours and =Parsec='s is that mine does not consume the end
parser's result.

#+NAME: Parser
#+BEGIN_SRC haskell
manyTill :: Parser a -> Parser end -> Parser [a]
manyTill p = P.manyTill p . P.lookAhead

many1Till :: Parser a -> Parser end -> Parser [a]
many1Till p = liftM2 (:) p . manyTill p
#+END_SRC

#+NAME: Parser
#+BEGIN_SRC haskell
eitherMany1 :: Parser end -> Parser a -> Parser (Either end [a])
eitherMany1 end p =
  (Left <$> P.try end) <|>
  (Right <$> many1Till p (void endOfLine <|> void end))
#+END_SRC

** Document

With the basic things out of the way, let's start by parsing a
document. It consists of a prelude of keywords followed by an
arbitrary number of sections. The parser follows naturally.

#+NAME: Parser
#+BEGIN_SRC haskell
instance Parse Document where
  parse = do
    _ <- parserTrace "Document" ()
    hs <- P.many parse :: Parser [Keyword]
    P.updateState $ \s -> s{ propertyStack = Stack [headerProperties hs] }
    skipEmptyLines
    _ <- parserTrace "Document:Sections" ()
    ss <- P.many . P.try $ parse :: Parser [Section]
    _ <- parserTrace "Document:/Sections" ()
    skipEmptyLines *> P.eof
    parserTrace "/Document" $ Document { keywords = hs , sections = ss }
#+END_SRC

In order to invoke this parser, I need to first have an ~OrgLines~
instance, and a properly initialized parser state. All of that logic
is put together in the ~readOrgFile~ function below.

#+NAME: Parser
#+BEGIN_SRC haskell
readOrgFile :: LogLevel -> FilePath -> IO (OrgLines, Document)
readOrgFile lvl fp = do
  ingested <- fromList <$> ingest fp :: IO OrgLines
  <<Build the evaluation context ~ctx~>>
  let doc = fromEither $ P.runParser
        (parse :: Parser Document)
        initialParserState{ evalContext = ctx, parserLogLevel = lvl }
        fp
        ingested
  return (ingested, doc)
#+END_SRC

The evaluation context contains things Emacs knows about, such as
~system-type~, and things it doesn't but that I provide anyway, such
as DMI information.

#+NAME: Build the evaluation context ~ctx~
#+BEGIN_SRC haskell
let styp = ( Atom "system-type"
           , Atom $ case Sys.os of
                      "linux" -> "gnu/linux"
                      "mingw32" -> "windows-nt"
                      o -> o
           )
    atomize k = fmap ((Atom k,) . Atom)
hnam <- (SExpr [Atom "system-name"],) . Atom <$> getHostName
pfam <- atomize "dmi/product-family"  <$> (<<Read DMI property>>) "product_family"
pnam <- atomize "dmi/product-name"    <$> (<<Read DMI property>>) "product_name"
pver <- atomize "dmi/product-version" <$> (<<Read DMI property>>) "product_version"

let ctx = Map.fromList $ styp : hnam : catMaybes [pfam, pnam, pver]
#+END_SRC

In a Linux system, the DMI properties are located in a =sys= sub-directory.

#+NAME: Read DMI property
#+BEGIN_SRC haskell
\p -> either (\_ -> Nothing) (Just . reverse . dropWhile isSpace . reverse)
     <$> (E.try (readFile $ "/sys/devices/virtual/dmi/id" F.</> p)
          :: IO (Either E.IOException String))
#+END_SRC

The =Sys.os= variable requires the import of =System.Info=, and =try=
is from =System.IO.Error=

#+NAME: Imports
#+BEGIN_SRC haskell
import qualified System.Info as Sys
import qualified Control.Exception as E
#+END_SRC

** Markup

I tried to follow the
[[https://orgmode.org/worg/dev/org-syntax.html#Emphasis_Markers][rules]] for
parsing markup somewhat closely, but there will be some
differences. The rules state that markup is of the form
$$\hbox{{\tt PRE MARKER BORDER BODY BORDER MARKER POST},}$$
where the intricacies of the meaning of the components is so that one
can write things like
$$\hbox{\tt and/or and this/that}$$
without implying that
``or and this'' should be in italics.
I chose to ignore the =BORDER= rules, as I want to be able to use any
character inside a markup.

§ The character just before the marker, =PRE=, must be one of the ones
below, or be the beginning of a line. Since I can't test for the
latter by consuming a character, the parser returns a ~Maybe Char~.

#+NAME: Parse the character before a markup
#+BEGIN_SRC haskell
(beginningOfLine *> return Nothing)
<|> (Just <$> satisfy (\c -> isSpace c || elem c "({'\""))
:: Parser (Maybe Char)
#+END_SRC

A different rule applies for the character just after the markup, but
the situation is the same with =eof= replaced for the beggining of a line.

#+NAME: Parse the first character after a markup
#+BEGIN_SRC haskell
(P.eof *> return Nothing)
<|> Just <$> satisfy (\c -> isSpace c || elem c "-.,:!?)}'\"")
<|> Just <$> endOfLine
:: Parser (Maybe Char)
#+END_SRC

A markup starts with a sequence =PRE MARKER=, which is parsed
below. The parser returns =PRE=, in case it is not the beginning of
the line, the =MARKER= found, and places the parsing stream ready to
parse the markup body.

#+NAME: Parse the start of markup
#+BEGIN_SRC haskell
P.try $ liftM2 (,)
  (<<Parse the character before a markup>>)
  (P.oneOf "*~/+=")
:: Parser (Maybe Char, Char)
#+END_SRC

A markup ends with =MARKER END=. That is
parsed below a parser that returns nothing, and places the stream
right before the first thing after the markup.

#+NAME: Parse the end of markup ~marker~
#+BEGIN_SRC haskell
P.try $
  void (P.char marker)
  <* P.lookAhead (<<Parse the first character after a markup>>)
:: Parser ()
#+END_SRC

I am now finally ready to parse a marked up text. After parsing the
markup start, I read all the characters until the end of
the markup with the ~manyTill~ parser. The rest is
simple, except for some markups that accept nested markups, where the
process is repeated by parsing ~Text~ again from the body with
~textFromString~.

#+NAME: Parse a markup text element
#+BEGIN_SRC haskell
P.try $ do
  (pre, marker) <-
    (>>= parserTrace "Text:Markup:/Start")
    (<<Parse the start of markup>>)
  p <- P.getPosition
  body <-
    (>>= parserTrace "Text:Markup:/BodyA")
    (manyTill anyChar (<<Parse the end of markup ~marker~>>))
  _ <- char marker
  return . (pre,) $ case marker of
    '*' -> Bold $ textFromString p body
    '~' -> InlineCode body
    '/' -> Italics $ textFromString p body
    '+' -> StrikeThrough body
    '=' -> Verbatim body
    e   -> error $ "unknown markup marker '" ++ show e ++ "'"
:: Parser (Maybe Char, TextElement)
#+END_SRC

The ~textFromString~ function, in turn, is a simple call to
~runParser~.

#+NAME: Parser
#+BEGIN_SRC haskell
textFromString :: P.SourcePos -> String -> Text
textFromString p s = fromEither $ P.runParser
    (parse :: Parser Text)
    initialParserState
    (P.sourceName p)
    (OrgLines [OrgLine p s])
#+END_SRC

I might as well introduce a related parser, ~textTill~, which collects
all characters until a given parser succeeds, then parses what was
collected as ~Text~.

#+NAME: Parser
#+BEGIN_SRC haskell
textTill :: Parser end -> Parser Text
textTill end = do
  _ <- parserTrace "TextTill" ()
  p <- P.getPosition
  t <- P.manyTill anyChar end
  parserTrace "/TextTill" $ textFromString p t
#+END_SRC

That out of the way, I parse other text elements. The next one is
inlined $\hbox{\TeX}$ math formulas. For both of them, I'm currently
assuming there's no other reason to have dollar signs in Org text. I
will change this when I find one.

#+NAME: Parse inline $\TeX$
#+BEGIN_SRC haskell
(DisplayMath <$>
  (P.try (P.string "$$")
   *> P.manyTill P.anyChar (P.try $ P.string "$$")))
<|>
(InlineMath <$>
  (P.char '$'
   *> P.manyTill P.anyChar (P.char '$')))
:: Parser TextElement
#+END_SRC

Hyperlinks have two variations, =[[URL]]= and =[[URL][TEXT]]=. The second one
supports embedded markup, using the ~textTill~ parser defined above.

#+NAME: Parse a hyperlink
#+BEGIN_SRC haskell
do
  url <- P.string "[[" *> many1Till anyChar (P.string "][" <|> P.string "]]")
  txt <- P.string "][" <|> P.string "]]" >>= \case
    "]]" -> return $ Text [Verbatim url]
    _    -> textTill (P.string "]]")
  return $ HyperLink url txt
#+END_SRC

** Text

With markup parsing in place, we can finally tackle parsing text. I
will do it accumulating one character at a time with the
occasional markup along the way. The accumulator is then a pair,
=(String, [TextElement])=, where the string is the currently
accumulated plain text, and the list is all the text elements that
came before it. With this accumulation done in a ~scanText~ function, the
text parser is given below.

#+NAME: Parser
#+BEGIN_SRC haskell
instance Parse Text where
  parse = do
    _ <- parserTrace "Text" ()
    ret <- reverse . snd <$> scanText ([], [])
    failWhen (null ret) P.<?> "empty text"
    parserTrace "/Text" $ Text ret
#+END_SRC

The basic operation on the accumulation pair is to add a plain text
character and/or a marked up element to it. When both are added at the
same time, the character is added first. All accumulations are done in
reverse order, so when I group the plain text I have to reverse the
string.

#+NAME: Update text accumulator pair ~acc~
#+BEGIN_SRC haskell
\(newChar, newMarkup) -> case (newChar, fst acc, newMarkup) of
  (Nothing, [], Nothing) -> ([], snd acc)
  (Nothing, cs, Nothing) -> ([], Plain (reverse cs) : snd acc)
  (Just c,  cs, Nothing) -> ([], Plain (reverse $ c : cs) : snd acc)
  (Nothing, [], Just m)  -> ([], m : snd acc)
  (Nothing, cs, Just m)  -> ([], m : Plain (reverse cs) : snd acc)
  (Just c,  cs, Just m)  -> ([], m : Plain (reverse $ c : cs) : snd acc)
#+END_SRC

With that, here is ~scanText~: it either decides it is done, has found
some markup, or, if none of those, has seen a plain text
character. For all but the first options, it calls itself again with
an updated accumulator.

#+NAME: Parser
#+BEGIN_SRC haskell
scanText :: (String, [TextElement]) -> Parser (String, [TextElement])
scanText acc@(plain, text) =
  <<Stop parsing text at the end of a line>>
  <|> (<<Stop parsing text when something else starts>>)
  <|>
  (do
      markup <- P.try (<<Parse a hyperlink>>) >>= parserTrace "Text/Link"
      scanText $ (<<Update text accumulator pair ~acc~>>) (Nothing, Just markup)
  )
  <|>
  (do
      markup <- P.try (<<Parse inline $\TeX$>>) >>= parserTrace "Text/TeX"
      scanText $ (<<Update text accumulator pair ~acc~>>) (Nothing, Just markup)
  )
  <|>
  (do
      (maybePre, markup) <- (<<Parse a markup text element>>) >>= parserTrace "Text:/Markup"
      scanText $ (<<Update text accumulator pair ~acc~>>) (maybePre, Just markup)
  )
  <|> (anyChar >>= scanText . (,text) . (:plain))
#+END_SRC

Text is parsed line by line.

#+NAME: Stop parsing text at the end of a line
#+BEGIN_SRC haskell
(P.eof *> parserTrace "Text:/EOF"
  ((<<Update text accumulator pair ~acc~>>) (Nothing, Nothing)))
<|> (endOfLine *> parserTrace "Text:/EOL"
  ((<<Update text accumulator pair ~acc~>>) (Nothing, Nothing)))
#+END_SRC

Text also stops when something else starts, and at the moment
/something else/ is one of the explicit things listed below.

#+NAME: Stop parsing text when something else starts
#+BEGIN_SRC haskell
do
  beginningOfLine
  P.lookAhead . P.choice $ map P.try
    [ void (spaces *> P.string "#+NAME")
    , void (spaces *> P.string "#+BEGIN_SRC")
    , void (parse :: Parser Headline)
    ]
  parserTrace "Text:/Break" $ (<<Update text accumulator pair ~acc~>>) (Nothing, Nothing)
#+END_SRC

** Properties

Properties appear in two places: in the document header, as a
=#+PROPERTY= line, and after section headlines in =:PROPERTIES:= drawers.

#+NAME: Parser
#+BEGIN_SRC haskell
instance Parse Properties where
  parse = do
    _ <- parserTrace "Properties" ()
    ps <- (<<Parse a =#+PROPERTY= line>>) <|> (<<Parse a =:PROPERTIES:= drawer>>)
    _ <- parserTrace "/Properties" ()
    return ps
#+END_SRC

A =#+PROPERTY= line specifies the property the line refers to,
followed by a list of key-value pairs.

#+NAME: Parse a =#+PROPERTY= line
#+BEGIN_SRC haskell
do
  _ <- P.try (P.string "#+PROPERTY:") *> spaces
  liftM2 Map.singleton
    (symbol <* spaces1)
    (<<Parse a line of property key-value pairs>>)
#+END_SRC

A =:PROPERTIES:= drawer is a sequence of lines specifying the
property name, followed by the list of key-value pairs.

#+NAME: Parse a =:PROPERTIES:= drawer
#+BEGIN_SRC haskell
do
  _ <- P.try (spaces *> P.string ":PROPERTIES:" *> spaces *> endOfLine)
  Map.fromList <$> P.manyTill
    (liftM2 (,)
       (spaces *> (enclosed ':' <* spaces))
       (<<Parse a line of property key-value pairs>>))
    (P.try (spaces *> P.string ":END:" *> spaces *> endOfLine))
#+END_SRC

A line of key-value pairs is a sequence of alternating symbols (the
property name) and S-expressions (the value). Those pairs have an
optional equals sign between them.

#+NAME: Parse a line of property key-value pairs
#+BEGIN_SRC haskell
line (Map.fromList
      <$> P.sepEndBy
       (liftM2 (,)
         (symbol <* (spaces1 <|> (spaces *> P.char '=' *> spaces)))
         (parse :: Parser SExpr))
       spaces1)
#+END_SRC

** S-Expressions

S-Expression are famously easy to parse. The only tweak I need to make
is in parsing Org boolean values, as org treats =no= as =nil=, and
=yes= as =t=.

#+NAME: Parser
#+BEGIN_SRC haskell
instance Parse SExpr where
  parse = (<<Parse a parenthesized S-expression>>)
          <|> (<<Parse a boolean property>>)
          <|> (<<Parse an ~Atom~>>)
#+END_SRC

A recursive parse takes care of lists.

#+NAME: Parse a parenthesized S-expression
#+BEGIN_SRC haskell
SExpr <$> ( P.try (P.char '(')
             *> spaces
             *> (P.sepEndBy (parse :: Parser SExpr) spaces1 <* P.char ')')
           )
#+END_SRC

A hardcoded list of possibilities takes care of Org truth-y values.

#+NAME: Parse a boolean property
#+BEGIN_SRC haskell
P.try (P.string "nil" *> P.lookAhead P.space *> return (SExpr []))
<|>
P.try (P.string "no" *> P.lookAhead P.space *> return (SExpr []))
<|>
P.try (P.string "yes" *> P.lookAhead P.space *> return (Atom "t"))
#+END_SRC

Finally, everything else is an atom. I am not making a distinction
between strings and symbols at this point.

#+NAME: Parse an ~Atom~
#+BEGIN_SRC haskell
Atom <$> (enclosed '"' <|> symbol)
#+END_SRC
