* Parsing

We will do some extra work during parsing to avoid multiple passes
over the structure, and in order to do that we will keep some
state. This state will contain the evaluation context (used when
evaluating s-expressions), the log level specified by the user, a
property stack, and the current section number.

#+NAME: Parser
#+BEGIN_SRC haskell
data ParserState = ParserState
  { sectionCounter :: Int
  , propertyStack  :: Stack Properties
  , evalContext    :: Map.Map SExpr SExpr
  , parserLogLevel :: LogLevel
  }
#+END_SRC

As with other things, we pretty-print it as a map.

#+NAME: Pretty printing
#+BEGIN_SRC haskell
instance Pretty ParserState where
  pretty = prettyStruct "ParserState"
    [ ("counter", pretty . sectionCounter)
    , ("eval context", pretty . evalContext)
    , ("log level", pretty . parserLogLevel)
    , ("property stack", pretty . propertyStack)
    ]
#+END_SRC

Based on this state, we define the main parser type, and a type class
to be instantiated by all things that know how to parse
themselves. The stream type is that of ~OrgLines~, which we will deal
with in the next section.

#+NAME: Parser
#+BEGIN_SRC haskell
type Parser = P.Parsec OrgLines ParserState

class Parse a where
  parse :: Parser a
#+END_SRC

** Lines of Input

Before parsing an Org file into a ~Document~, we will read its
contents as lines, expanding all the =#+INCLUDE= directives while at
it. The end result will be a list of lines where each line will
contain not only the contents of that line, but also the name of the
file it came from, and the line number in that file. This will be
important when inserting line pragmas while tangling.

#+NAME: Parser
#+BEGIN_SRC haskell
data OrgLine = OrgLine P.SourcePos String
#+END_SRC

We have to remove the trailing newline when pretty-printer, as the
decision to break a line or not is up to the pretty-printing algorithm.

#+NAME: Pretty printing
#+BEGIN_SRC haskell
instance Pretty OrgLine where
  pretty (OrgLine p l) =
    PP.hcat [pretty p, PP.colon, PP.text (takeWhile (/= '\n') l)]
#+END_SRC

Now to ingesting those lines. The parser we are going to use for both
ingesting and final parsing is =Parsec=.

#+NAME: Imports
#+BEGIN_SRC haskell
import qualified Text.Parsec as P
import qualified Text.Parsec.Pos as P
#+END_SRC

The Stack package for the boostrapper is =parsec=.

#+NAME: stack-packages
#+BEGIN_SRC shell
--package parsec
#+END_SRC

Ingesting a file is a matter of reading all of its lines, then recursively
replacing any =#+INCLUDE= directives by the files they
reference. Reading a file's lines can be done with the prelude's
~readFile~ and ~lines~ functions. We have to put back the lost
newlines to facilitate things later on.

#+NAME: Parser
#+BEGIN_SRC haskell
ingest :: FilePath -> IO [OrgLine]
ingest file = do
    zipWith OrgLine [P.newPos file l 1 | l <- [1..]] . map (++"\n") . lines
      <$> readFile file
      >>= foldrM scan []
  where
    scan l@(OrgLine pos s) ls =
      maybe (return (l : ls)) (fmap (++ ls) . ingest)
      $ (<<Parse an ~#+INCLUDE~ directive>> :: String -> Maybe FilePath) s
#+END_SRC

We invoke a parser to check whether the line is an =#+INCLUDE= line or
not, taking the precaution to set the position of the string to parse
to the correct position in the input file, so that errors are
properly reported.

#+NAME: Parse an ~#+INCLUDE~ directive
#+BEGIN_SRC haskell
fromEither . P.parse
(P.setPosition pos *>
    P.optionMaybe (
      P.try (P.spaces *> P.string "#+INCLUDE:" *> P.spaces)
      *> P.char '"'
      *> P.manyTill anyChar (P.char '"')
    ))
(P.sourceName pos)
#+END_SRC

The ~fromEither~ function above returns a successful result, or errors out
by pretty-printing the error. We will use it a handful of times more later.

#+NAME: Common =CCWEB= code
#+BEGIN_SRC haskell
fromEither :: Pretty a => Either a b -> b
fromEither = either (error . PP.render . pretty) id
#+END_SRC

We also used an ~anyChar~ parser above. It is similar to the one
defined by =Parsec=, except it does not cross line boundaries.

#+NAME: Parser
#+BEGIN_SRC haskell
anyChar :: (P.Stream s m Char) => P.ParsecT s u m Char
anyChar = P.noneOf "\n\r"
#+END_SRC

Now that we have an Org file ingested into a list of ~OrgLine~, we
need to make those available for the next parser as a ~P.Stream~.

#+NAME: Parser
#+BEGIN_SRC haskell
instance Monad m => P.Stream OrgLine m Char where
  uncons (OrgLine _ []) =
    return Nothing
  uncons (OrgLine p (x:xs)) =
    return $ Just (x, OrgLine (P.updatePosChar p x) xs)
#+END_SRC

The next piece of the ~P.Stream~ puzzle is to support lists of
~OrgLine~. We can't simply declare ~[OrgLine]~ an instance of ~Stream~
because that would conflict with then instance =Parsec= declares for
tokens. We get around it by wrapping the list in a new type.

#+NAME: Parser
#+BEGIN_SRC haskell
newtype OrgLines = OrgLines [OrgLine]
#+END_SRC

Pretty-printing this is rather trivial.

#+NAME: Pretty printing
#+BEGIN_SRC haskell
instance Pretty OrgLines where
  pretty (OrgLines ls) = pretty ls
#+END_SRC

This is now turned into a ~Stream~. In order to be able to obtain
valid positions for the end of file, I make sure to mark the end of
the stream based on the ~OrgLines~ having a single empty string left.

#+NAME: Parser
#+BEGIN_SRC haskell
instance Monad m => P.Stream OrgLines m Char where
  uncons (OrgLines (x:[])) = P.uncons x >>= \case
    Nothing -> return Nothing
    Just (x',xs') -> return $ Just (x', OrgLines (xs':[]))
  uncons (OrgLines (x:xs)) = P.uncons x >>= \case
    Nothing -> P.uncons (fromList xs :: OrgLines)
    Just (x',OrgLine _ []) -> return $ Just (x', OrgLines xs)
    Just (x',xs') -> return $ Just (x', OrgLines (xs':xs))
  uncons (OrgLines []) =
    error $ "(internal): uncons of empty OrgLines instance"
#+END_SRC

** Basic Parsers

When we talk about whitespace, we will be talking about
/horizontal whitespace/. The =Parsec= parsers don't have those, so we
implement them ourselves.

#+NAME: Parser
#+BEGIN_SRC haskell
space :: Parser Char
space = P.satisfy (\c -> isSpace c && notElem c "\n\r")

spaces :: Parser String
spaces = P.many space

spaces1 :: Parser String
spaces1 = P.many1 space
#+END_SRC

There will be a few places where we will need to parse a /symbol/,
which we fuzzily consider to be a ``variable name.'' The ~=~
character, for example, is a valid Lisp symbol name, but not a valid
Org property name.

#+NAME: Parser
#+BEGIN_SRC haskell
symbolChar :: Parser Char
symbolChar = P.satisfy (\c -> isPrint c && not (isSpace c) && notElem c "()=")

symbol :: Parser String
symbol = P.many1 symbolChar
#+END_SRC

In order to make use of the positions reported by an ~OrgLines~
stream, we need to re-define a few basic =Parsec= parsers. The only
meaningful change is in ~satisfy~. The standard implementation updates
the position according to the character just consumed, meaning the
parser always ``thinks'' it is in the same file. Our implementation
will use the location stored in the current ~OrgLine~, each of which
may come from a different file.

#+NAME: Parser
#+BEGIN_SRC haskell
satisfy :: (Char -> Bool) -> Parser Char
satisfy f = P.tokenPrim
            (\c -> show [c])
            (\pos _ (OrgLines rest) ->
               case rest of
                 (OrgLine pos' _):_ -> pos'
                 [] -> error $ show pos ++ ": (internal) empty OrgLines")
            (\c -> if f c then Just c else Nothing)
#+END_SRC

The only parser we /really/ need to re-define for positioning purposes
is ~endOfLine~, because it is only when changing lines that positions
can switch from one source file to another in an ~OrgLine~. We will do
it by replicating the relevant =Parsec= definitions, substituting our
~satisfy~ in the only place where it shows up.

#+NAME: Parser
#+BEGIN_SRC haskell
char :: Char -> Parser Char
char c = satisfy (==c) P.<?> show [c]

newline :: Parser Char
newline = char '\n' P.<?> "lf new-line"

crlf :: Parser Char
crlf = char '\r' *> char '\n' P.<?> "crlf new-line"

endOfLine :: Parser Char
endOfLine = newline <|> crlf P.<?> "new-line"
#+END_SRC

There are places where I need to check whether or not the parser is
positioned at the start of a line. This is more complicated, because
it is not indicated by the character I am looking at, but at the
/position/ of the character.

#+NAME: Parser
#+BEGIN_SRC haskell
beginningOfLine :: Parser ()
beginningOfLine = do
  c <- P.sourceColumn <$> P.getPosition
  succeedWhen (c == 1)
#+END_SRC

The ~succeedWhen~ parser used above, and the corresponding ~failWhen~,
are trivially implemented in terms of ~satisfy~.

#+NAME: Parser
#+BEGIN_SRC haskell
succeedWhen :: Bool -> Parser ()
succeedWhen True = return ()
succeedWhen False = void $ satisfy (\_ -> False)

failWhen :: Bool -> Parser ()
failWhen = succeedWhen . not
#+END_SRC

** Parser Combinators

The ~manyTill~ parser parses something until something else
appears, then returns the list of things parsed. The only difference
between ours and =Parsec='s is that ours does not consume the end
parser's result.

#+NAME: Parser
#+BEGIN_SRC haskell
manyTill :: Parser a -> Parser end -> Parser [a]
manyTill p = P.manyTill p . P.lookAhead

many1Till :: Parser a -> Parser end -> Parser [a]
many1Till p = liftA2 (:) p . manyTill p
#+END_SRC

#+NAME: Parser
#+BEGIN_SRC haskell
eitherMany1 :: Parser end -> Parser a -> Parser (Either end [a])
eitherMany1 end p =
  (Left <$> P.try end) <|>
  (Right <$> many1Till p (void endOfLine <|> void end))
#+END_SRC

** Markup

I tried to follow the
[[https://orgmode.org/worg/dev/org-syntax.html#Emphasis_Markers][rules]] for
parsing markup somewhat closely, but there will be some
differences. The rules state that markup is of the form
$$\hbox{{\tt PRE MARKER BORDER BODY BORDER MARKER POST},}$$
where the intricacies of the meaning of the components is so that one
can write things like ``and/or and this/that'' without implying that
``or and this'' should be in italics.

The first and last characters of a markup text must match what the Org
reference calls a ``border.'' I allow double-quotes.

#+NAME: Parse a markup border character
#+BEGIN_SRC haskell
satisfy (\c -> not (isSpace c) && notElem c ",'")
:: Parser Char
#+END_SRC

The character just before the marker, the ``pre'' character,
must be one of the ones below, or be the beginning of a line. Since
we can't test for the latter by consuming a character, the parser
returns a ~Maybe Char~.

#+NAME: Parse the character before a markup
#+BEGIN_SRC haskell
(beginningOfLine *> return Nothing)
<|> (Just <$> satisfy (\c -> isSpace c || elem c "({'\""))
:: Parser (Maybe Char)
#+END_SRC

A different rule applies for the character just after the markup, but
the situation is the same with =eof= replaced for the beggining of a line.

#+NAME: Parse the first character after a markup
#+BEGIN_SRC haskell
(P.eof *> return Nothing)
<|> Just <$> satisfy (\c -> isSpace c || elem c "-.,:!?)}'\"")
<|> Just <$> endOfLine
:: Parser (Maybe Char)
#+END_SRC

A markup starts with a sequence =PRE MARKER BORDER=, which is parsed
below. The parser returns =PRE=, in case it is not the beginning of
the line, the =MARKER= found, and places the parsing stream ready to
parse =BORDER=.

#+NAME: Parse the start of markup
#+BEGIN_SRC haskell
P.try $ do
  p <- (<<Parse the character before a markup>>)
  m <- (P.oneOf "*~/+=")
  _ <- P.lookAhead (<<Parse a markup border character>>)
  return (p,m)
:: Parser (Maybe Char, Char)
#+END_SRC

A markup ends with =BORDER MARKER END=. The Org rules mentioned below
seem to imply that the border that starts a markup can not be the one
that ends it, but I support that case (and so does Org). That is
parsed below a parser that returns =BORDER= and places the stream
right before the first thing after the markup.

#+NAME: Parse the end of markup ~marker~
#+BEGIN_SRC haskell
P.try $
  (<<Parse a markup border character>>)
  <* P.char marker
  <* P.lookAhead (<<Parse the first character after a markup>>)
:: Parser Char
#+END_SRC

I am now finally ready to parse a marked up text. After parsing the
markup start, I read all the characters until the last =BORDER=
character with the ~manyTill~ parser. I then parse =BORDER= with
~anyChar~ and combine the two to get the markup body. The rest is
simple, except for some markups that accept nested markups, where the
process is repeated by parsing ~Text~ again from the body with
~textFromString~.

#+NAME: Parse a markup text element
#+BEGIN_SRC haskell
P.try $ do
  (pre, marker) <- (>>= parserTrace "Text:Markup:/Start") (<<Parse the start of markup>>)
  p <- P.getPosition
  b1 <- (>>= parserTrace "Text:Markup:/BodyA") (manyTill anyChar (<<Parse the end of markup ~marker~>>))
  b2 <- (>>= parserTrace "Text:Markup:/BodyB") ((:[]) <$> anyChar)
  _ <- char marker
  let body = b1 ++ b2
  return . (pre,) $ case marker of
    '*' -> Bold $ textFromString p body
    '~' -> InlineCode body
    '/' -> Italics $ textFromString p body
    '+' -> StrikeThrough body
    '=' -> Verbatim body
    e   -> error $ "unknown markup marker '" ++ show e ++ "'"
:: Parser (Maybe Char, TextElement)
#+END_SRC

#+NAME: Parse inline $\TeX$
#+BEGIN_SRC haskell
(DisplayMath <$> (P.try (P.string "$$") *> P.manyTill P.anyChar (P.try $ P.string "$$")))
<|>
(InlineMath <$> (P.char '$' *> P.manyTill P.anyChar (P.char '$')))
:: Parser TextElement
#+END_SRC

#+NAME: Parse a hyperlink
#+BEGIN_SRC haskell
P.try $ do
  url <- P.string "[[" *> many1Till anyChar (P.string "][" <|> P.string "]]")
  txt <- P.string "][" <|> P.string "]]" >>= \case
    "]]" -> return $ Text [Verbatim url]
    _    -> textTill (P.string "]]")
  let hyp = HyperLink url txt
  _ <- parserTrace "Text:/HyperLink" hyp
  textAcc $ ([], hyp : upx Nothing plain text)
#+END_SRC

** Text

With markup parsing in place, we can finally tackle parsing text. We
will do it using a fold that keeps track of the plain text parsed
since the last markup, and the current text line.

#+NAME: Parser
#+BEGIN_SRC haskell
upx :: Maybe Char -> String -> [TextElement] -> [TextElement]
upx Nothing  []    elts = elts
upx Nothing  plain elts = Plain (reverse plain) : elts
upx (Just c) plain elts = Plain (reverse $ c : plain) : elts
#+END_SRC

#+NAME: Parser
#+BEGIN_SRC haskell
textAcc :: (String, [TextElement]) -> Parser (String, [TextElement])
textAcc (plain, text) =
  <<Stop parsing text at the end of a line>>
  <|> (<<Stop parsing text when something else starts>>)
  <|> (<<Parse a hyperlink>>)
  <|>
  (do
      markup <- P.try (<<Parse inline $\TeX$>>) >>= parserTrace "Text/TeX"
      textAcc $ ([], markup : upx Nothing plain text)
  )
  <|>
  (do
      (c, markup) <- (<<Parse a markup text element>>) >>= parserTrace "Text:/Markup"
      textAcc $ ([], markup : upx c plain text)
  )
  <|> (anyChar >>= textAcc . (,text) . (:plain))
#+END_SRC

#+NAME: Stop parsing text at the end of a line
#+BEGIN_SRC haskell
(P.eof *> parserTrace "Text:/EOF" ([], upx Nothing plain text))
<|> (endOfLine *> parserTrace "Text:/EOL" ([], upx Nothing plain text))
#+END_SRC

#+NAME: Stop parsing text when something else starts
#+BEGIN_SRC haskell
do
  beginningOfLine
  P.lookAhead . P.choice $ map P.try
    [ void (spaces *> P.string "#+NAME")
    , void (spaces *> P.string "#+BEGIN_SRC")
    , void (parse :: Parser Headline)
    ]
  parserTrace "Text:/Break" ([], upx Nothing plain text)
#+END_SRC

#+NAME: Parser
#+BEGIN_SRC haskell
textTill :: Parser end -> Parser Text
textTill end = do
  _ <- parserTrace "TextTill" ()
  p <- P.getPosition
  t <- P.manyTill anyChar end
  parserTrace "/TextTill" $ textFromString p t
#+END_SRC

#+NAME: Parser
#+BEGIN_SRC haskell
instance Parse Text where
  parse = do
    _ <- parserTrace "Text" ()
    ret <- reverse . snd <$> textAcc ([], [])
    failWhen (null ret) P.<?> "empty text"
    _ <- parserDebug "/Text" ret

    return $ Text ret
#+END_SRC

#+NAME: Parser
#+BEGIN_SRC haskell
textFromString :: P.SourcePos -> String -> Text
textFromString p s = fromEither $ P.runParser
    (parse :: Parser Text)
    initialParserState
    (P.sourceName p)
    (OrgLines [OrgLine p s])
#+END_SRC
