* The Tangler

#+BEGIN_SRC haskell :tangle "bin/cctangle.hs" :tangle-mode (identity #o444)
<<Common-ccweb-code>>
<<Tangler>>
#+END_SRC

#+NAME: Tangler
#+BEGIN_SRC haskell
main :: IO ()
main = do
  opts <- O.execParser optParser
  logM (logLevel opts) Info $ "This is CCWEB"

  (ingested, doc) <- readOrgFile (inputFile opts)
  logM (logLevel opts) Debug $ PP.render (pretty ingested)
  logM (logLevel opts) Debug $ PP.render (pretty doc)

  home <- Env.getEnv "HOME"
  let outs = <<Gather blocks to tangle to files>> :: [(FilePath, [SourceBlock])]
  <<List input and output files>>

  mapM_ (tangleFile opts doc) outs
  where
    optParser = O.info (userOptionParser <**> O.helper)
      ( O.fullDesc
      <> O.progDesc "Tangle the input FILE"
      <> O.header "cctangle - A literate programming tangler" )
#+END_SRC

Gathering and grouping the top level code blocks is a trivial but long
sequence of filters and transformations on the document source blocks: I
select the ones that are not named, and for which the =:tangle=
parameter is a file name. I then group those by file name into
=(FilePath,[SourceBlock])= pairs.

#+NAME: Gather blocks to tangle to files
#+BEGIN_SRC haskell
(map (\bs -> (fst (head bs), map snd bs))
     :: [[(FilePath, SourceBlock)]] -> [(FilePath,[SourceBlock])])
  . (groupWith fst
     :: [(FilePath, SourceBlock)] -> [[(FilePath, SourceBlock)]])
  . (sortWith fst
     :: [(FilePath, SourceBlock)] -> [(FilePath, SourceBlock)])
  . (map (\(fp,b) -> (case fp of { ('~':xs) -> home ++ xs; _ -> fp }, b))
     :: [(FilePath, SourceBlock)] -> [(FilePath, SourceBlock)])
  . (mapMaybe (\b -> (flip (,) b) <$> blockFile b)
     :: [SourceBlock] -> [(FilePath,SourceBlock)])
  . (mapMaybe sectionSourceBlock
     :: [Section] -> [SourceBlock])
  $ orgSections doc
#+END_SRC

Once I have the input file ~ingested~ and parsed, I can print out all
the input and output files. The former are listed in the ~ingested~
lines, and the latter are the first element of the ~outs~ tuples.

#+NAME: List input and output files
#+BEGIN_SRC haskell
when (listOutputFiles opts) $ mapM_ putStrLn (map fst outs)
when (listInputFiles opts)  $ mapM_ putStrLn (
  nub . sort .
  map (\(OrgLine p _) -> P.sourceName p) $ (toList ingested)
  )
#+END_SRC

The file will be tangled by producing a sequence of code lines, which
can be either regular code text or ~LinePragma~ lines. The latter tell
the target compiler where in the Org file the source lines originally came
from.

#+NAME: Tangler
#+BEGIN_SRC haskell
data Line = CodeText String | LinePragma String P.SourcePos
#+END_SRC

The line pragmas are different for different languages. =cctangle=
supports a few.

#+NAME: Tangler
#+BEGIN_SRC haskell
instance Show Line where
  show (CodeText str) = str ++ "\n"
  <<Line pragmas for known languages>>
  show (LinePragma _ _) = []
#+END_SRC

In Haskell, the format is ={-# LINE 123 "file" -#}=.

#+NAME: Line pragmas for known languages
#+BEGIN_SRC haskell
show (LinePragma "haskell" pos) = unwords
  [ "{-# LINE", show (P.sourceLine pos)
  , "\"" ++ P.sourceName pos ++ "\""
  , "#-}\n" ]
#+END_SRC

In =C= and =C++=, the format is =#line 123 "file"=.

#+NAME: Line pragmas for known languages
#+BEGIN_SRC haskell
show (LinePragma "c" pos) = unwords
  [ "#line", show (P.sourceLine pos)
  , "\"" ++ P.sourceName pos ++ "\"\n"
  ]
show (LinePragma "c++" pos) = show (LinePragma "c" pos)
#+END_SRC

The tangling process may generate more ~LinePragma~ lines than
necessary. The resulting file will be correct, but a bit too ugly. The
following will remove most of the redundant lines, and the ones that
remain are not too distasteful.

#+NAME: Remove redundant line pragmas
#+BEGIN_SRC haskell
foldr (\x xs ->
         let redundant (p1,n,p2) =
               P.sourceName p1 == P.sourceName p2
               && P.sourceLine p1 + n == P.sourceLine p2
         in case (x:xs) of
              (LinePragma _ _ : LinePragma _ _ : _) -> xs
              (LinePragma _ p1 : l1 : LinePragma _ p2 : xs') ->
                if redundant (p1,1,p2); then x : l1 : xs'; else (x:xs)
              _ -> (x:xs))
      []
#+END_SRC

I will need to keep track of the current indentation while tangling
regular code lines, so that expansion of source block references
retain their original indentation.

#+NAME: Tangler
#+BEGIN_SRC haskell
type Indent = String
#+END_SRC

This indentation is kept in a ~TangleState~ object that gets updated
as tangling moves along. Three other pieces of information will be needed:
the original document, so I can expand references; a stack of
source blocks currently being tangled, so I can access the currently
active set of Org properties; and the language to use for line pragmas.

#+NAME: Tangler
#+BEGIN_SRC haskell
data TangleState = TangleState
  { document :: Document
  , indent :: Indent
  , blocks :: Stack SourceBlock
  , pragmaLanguage :: String
  }
#+END_SRC

As the name implies, I treat this as a proper state, using the ~State~
monad, for which I define a few state access and modification functions.

#+NAME: Tangler
#+BEGIN_SRC haskell
type Tangler a = State TangleState a

getTopBlock :: Tangler SourceBlock
getTopBlock = top . blocks <$> get

getIndent :: Tangler Indent
getIndent = indent <$> get

setIndentFrom :: String -> Tangler ()
setIndentFrom str = modify
  (\s -> s{ indent = replicate (length str) ' ' })

addIndentFrom :: String -> Tangler ()
addIndentFrom str = modify
  (\s -> s{ indent = indent s ++ replicate (length str) ' ' })
#+END_SRC

Tangling source blocks is a matter of tangling all the block lines --
with an up-to-date state's block stack -- and adding an optional line
pragma indicating the location of the block's first line.

#+NAME: Tangler
#+BEGIN_SRC haskell
tangleSourceBlock :: SourceBlock -> Tangler [Line]
tangleSourceBlock block = do
  modify (\s -> s{ blocks = push block (blocks s) })
  ls <- concat <$> mapM tangleCodeLine (blockLines block)
  modify (\s -> s{ blocks = pop (blocks s) })
  maybeAddLinePragma ls (blockLocation block) block
#+END_SRC

#+NAME: Tangler
#+BEGIN_SRC haskell
maybeAddLinePragma :: [Line] -> P.SourcePos -> SourceBlock -> Tangler [Line]
maybeAddLinePragma ls pos block = do
  lang <- pragmaLanguage <$> get
  return $ case headerArg ":comments" block of
    Just (YesNo True) -> LinePragma lang pos : ls
    _ -> ls
#+END_SRC

Tangling code lines is a lot more complicated. The simple case is
tangling the empty line: all I need to do is to add the current
indentation to it.

#+NAME: Tangler
#+BEGIN_SRC haskell
tangleCodeLine :: CodeLine -> Tangler [Line]
tangleCodeLine (CodeLine _ []) = (:[]) . CodeText <$> getIndent
<<Tangle non-empty code line>>
#+END_SRC

Tangling a non-empty code line is a matter of tangling all of its
elements and stitching them together. This is complicated by two
things:

- A single element can result in multiple lines if it is a reference
  expansion. It is not uncommon for a "code line" to expand into a
  large part of the entire program.

- Those multiple lines have to be properly indented, which means I have to keep
  track of indentation as I go.

This is what I am going to do: I am going to tangle one element at a
time, and accumulate all that was tangled so far (in reverse order) in
a list of lines.

#+NAME: Tangle all ~element~s
#+BEGIN_SRC haskell
reverse <$> foldlM
  (<<Tangle the next element and update the accumulated tangled lines>>)
  [CodeText initialIndent] elements
#+END_SRC

#+NAME: Tangle non-empty code line
#+BEGIN_SRC haskell
tangleCodeLine (CodeLine _ elements) =
  do
    initialIndent <- getIndent
    ls <- removeLeadingEmptyLine . <<Tangle all ~element~s>>
    modify (\s -> s{ indent = initialIndent })
    getTopBlock >>= maybeAddLinePragma ls (getPosition $ head elements)
      where
        removeLeadingEmptyLine :: [Line] -> [Line]
        removeLeadingEmptyLine a@(CodeText l:p@(LinePragma _ _):ls)
          | all isSpace l = p:ls
          | otherwise = a
        removeLeadingEmptyLine a = a
#+END_SRC

It will be useful to be able to separate the accumulated lines into a
tail of pragma lines and and the remainder code text and pragma mix.

#+NAME: Tangler
#+BEGIN_SRC haskell
breakCodeText :: [Line] -> ([Line],[Line])
breakCodeText = break (\case { (CodeText _) -> True; _ -> False })
#+END_SRC

Since the accumulated line list will be in reverse order, the very
first line of ~snd . breakCodeText~ will contain the last tangled code
text line.

#+NAME: Tangle the next element and update the accumulated tangled lines
#+BEGIN_SRC haskell
\acc element -> do
  let (accPragmas, accRest) = breakCodeText acc
  case (accPragmas, accRest, element) of
    <<Tangle an ~(accPragmas, accRest, element)~ tuple>>
    _ -> error $ "unreachable element tangling case"
#+END_SRC

The first case is the simplest: when there are no pragmas, and a
literal is to be tangled, all I do is append that literal to the last
tangled line, and update the current indentation.

#+NAME: Tangle an ~(accPragmas, accRest, element)~ tuple
#+BEGIN_SRC haskell
([], (CodeText l:ls), Literal _ s) -> do
  addIndentFrom s
  return $ CodeText (l ++ s) : ls
#+END_SRC

The second case is of a literal with a line pragma following it. In
that case, I have to add the literal with the right indentation, and
add yet another line pragma to properly re-position the code. Again, I
update the current indentation.

#+NAME: Tangle an ~(accPragmas, accRest, element)~ tuple
#+BEGIN_SRC haskell
(_, _, Literal pos s) -> do
  i <- getIndent
  addIndentFrom s
  getTopBlock >>= maybeAddLinePragma (CodeText (i ++ s) : acc) pos
#+END_SRC

Now for the last and rather involved case: tangling a section
reference. I first tangle the section reference, getting back a list
of lines. I then update the line accumulator, which is the involved
part. The basic logic is as follows:

- If there are no pragmas, then the first reference line has to be
  appended to the last accumulated line, but it needs to be unindented
  first, because it will be regularly indented.
- If there are pragmas, the reference lines and their pragmas have to
  be added, in reverse, to the accumulator.

#+NAME: Tangle an ~(accPragmas, accRest, element)~ tuple
#+BEGIN_SRC haskell
(_, (CodeText l:ls), SectionReference pos name) -> do
  refLines <- <<Get the tangled lines for a section reference named ~name~>>
  let (refPragmas, (CodeText first : rest)) = breakCodeText refLines
  acc' <- case (refPragmas, accPragmas) of
    ([], []) -> do
      unindented <- <<Remove current indent from string>> first
      addIndentFrom unindented
      return $ reverse rest ++ (CodeText(l ++ unindented) : ls)
    _ -> do
      setIndentFrom first
      return $ reverse refLines ++ acc
  getTopBlock >>= maybeAddLinePragma acc' pos
#+END_SRC

#+NAME: Get the tangled lines for a section reference named ~name~
#+BEGIN_SRC haskell
do
  bs <- <<Gather code blocks named ~name~>> :: Tangler [SourceBlock]
  when (null bs) (error $ "source block not defined anywhere: " ++ show name)
  concat <$> mapM tangleSourceBlock bs :: Tangler [Line]
#+END_SRC

#+NAME: Gather code blocks named ~name~
#+BEGIN_SRC haskell
filter (\b -> case (blockName b) of
               Nothing -> False
               Just t -> t == name)
  . mapMaybe sectionSourceBlock
  . orgSections
  . document
  <$> get
#+END_SRC

#+NAME: Remove current indent from string
#+BEGIN_SRC haskell
(\str -> do
   i <- getIndent
   return $ if isPrefixOf i str; then drop (length i) str; else str
)
#+END_SRC

All that remains to do now is the unfinished ~IO~ business called from
the ~main~ routine.

#+NAME: Tangler
#+BEGIN_SRC haskell
tangleFile :: Options -> Document -> (FilePath, [SourceBlock]) -> IO ()
tangleFile opts _ (fp, []) =
  logM (logLevel opts) Warning $ "Not writing empty output file (" ++ fp ++ ")"
tangleFile opts doc (fp, bs) = do
  let block = head bs
      ls = concatMap
           (\b -> fst $ runState (tangleSourceBlock b)
                 TangleState{ document = doc
                            , indent = []
                            , blocks = Stack []
                            , pragmaLanguage = blockLanguage block }
           )
           bs
      contents = concatMap show $ <<Remove redundant line pragmas>> ls
  logM (logLevel opts) Info $ "Writing the output file (" ++ fp ++ ")"
  if dryRun opts
    then logM (logLevel opts) Info contents
    else do
      let dir = F.takeDirectory fp
      when (mkDir && dir /= ".") $ D.createDirectoryIfMissing True dir

      exists <- F.fileExist fp
      when exists $ F.removeLink fp

      writeFile fp contents
      case headerArg ":tangle-mode" block of
        Nothing -> return ()
        Just expr -> do
          let mode = fileMode expr
          F.setFileMode fp mode
  where
    mkDir = case headerArg ":mkdirp" (head bs) of
              Just (YesNo x) -> x
              _ -> False
#+END_SRC

#+NAME: Imports
#+BEGIN_SRC haskell
import qualified System.Directory as D
import qualified System.Environment as Env
import qualified System.FilePath as F
import qualified System.Posix.Files as F
import qualified System.Posix.Types as F
#+END_SRC

#+NAME: stack-packages
#+BEGIN_SRC shell
--package filepath
--package directory
--package unix
#+END_SRC
