* The Tangler

#+BEGIN_SRC haskell :tangle "bin/cctangle.hs" :tangle-mode (identity #o444)
<<Common-ccweb-code>>
<<Tangler>>
#+END_SRC

#+NAME: Tangler
#+BEGIN_SRC haskell
main :: IO ()
main = do
  opts <- O.execParser optParser
  logM (logLevel opts) Info $ "This is CCWEB"

  (ingested, doc) <- readOrgFile (inputFile opts)
  logM (logLevel opts) Debug $ PP.render (pretty ingested)
  logM (logLevel opts) Debug $ PP.render (pretty doc)

  home <- Env.getEnv "HOME"
  let outs = <<Gather blocks to tangle to files>> :: [(FilePath, [SourceBlock])]
  <<List input and output files>>

  mapM_ (tangleFile opts doc) outs
  where
    optParser = O.info (tanglerOptionParser <**> O.helper)
      ( O.fullDesc
      <> O.progDesc "Tangle the input FILE"
      <> O.header "cctangle - A literate programming tangler" )
#+END_SRC

As seen from the type of ~outs~, the output files are the first
elements in its tuples. The output files are all listed in the
lines of the ~ingested~ file.

#+NAME: List input and output files
#+BEGIN_SRC haskell
when (listOutputFiles opts) $ mapM_ putStrLn (map fst outs)
when (listInputFiles opts)  $ mapM_ putStrLn (
  nub . sort .
  map (\(OrgLine p _) -> P.sourceName p) $ (toList ingested)
  )
#+END_SRC

Gathering and grouping the top level code blocks is a trivial but long
sequence of filters and transformations on the document source blocks: I
select the ones that are not named, and for which the =:tangle=
parameter is a file name. I then group those by file name into
=(FilePath,[SourceBlock])= pairs.

#+NAME: Gather blocks to tangle to files
#+BEGIN_SRC haskell
(map (\bs -> (fst (head bs), map snd bs))
     :: [[(FilePath, SourceBlock)]] -> [(FilePath,[SourceBlock])])
  . (groupWith fst
     :: [(FilePath, SourceBlock)] -> [[(FilePath, SourceBlock)]])
  . (sortWith fst
     :: [(FilePath, SourceBlock)] -> [(FilePath, SourceBlock)])
  . (map (\(fp,b) -> (case fp of { ('~':xs) -> home ++ xs; _ -> fp }, b))
     :: [(FilePath, SourceBlock)] -> [(FilePath, SourceBlock)])
  . (mapMaybe (\b -> (flip (,) b) <$> blockFile b)
     :: [SourceBlock] -> [(FilePath,SourceBlock)])
  . (mapMaybe sectionSourceBlock
     :: [Section] -> [SourceBlock])
  $ orgSections doc
#+END_SRC

The file will be tangled by producing a sequence of code lines, which
can be either regular code text or ~LinePragma~ lines. The latter tell
the target compiler where in the Org file the source lines originally came
from.

#+NAME: Tangler
#+BEGIN_SRC haskell
data Line = CodeText String | LinePragma String P.SourcePos
#+END_SRC

The line pragmas are different for different languages. =cctangle=
supports a few.

#+NAME: Tangler
#+BEGIN_SRC haskell
instance Show Line where
  show (CodeText str) = str ++ "\n"
  <<Line pragmas for known languages>>
  show (LinePragma _ _) = []
#+END_SRC

In Haskell, the format is ={-# LINE 123 "file" -#}=.

#+NAME: Line pragmas for known languages
#+BEGIN_SRC haskell
show (LinePragma "haskell" pos) = unwords
  [ "{-# LINE", show (P.sourceLine pos)
  , "\"" ++ P.sourceName pos ++ "\""
  , "#-}\n" ]
#+END_SRC

In =C= and =C++=, the format is =#line 123 "file"=.

#+NAME: Line pragmas for known languages
#+BEGIN_SRC haskell
show (LinePragma "c" pos) = unwords
  [ "#line", show (P.sourceLine pos)
  , "\"" ++ P.sourceName pos ++ "\"\n"
  ]
show (LinePragma "c++" pos) = show (LinePragma "c" pos)
#+END_SRC

The tangling process may generate more ~LinePragma~ lines than
necessary. The resulting file will be correct, but a bit too ugly. The
following will remove most of the redundant lines, and the ones that
remain are not too distasteful.

#+NAME: Remove redundant line pragmas
#+BEGIN_SRC haskell
foldr (\x xs ->
         let redundant (p1,n,p2) =
               P.sourceName p1 == P.sourceName p2
               && P.sourceLine p1 + n == P.sourceLine p2
         in case (x:xs) of
              (LinePragma _ _ : LinePragma _ _ : _) -> xs
              (LinePragma _ p1 : l1 : LinePragma _ p2 : xs') ->
                if redundant (p1,1,p2); then x : l1 : xs'; else (x:xs)
              _ -> (x:xs))
      []
#+END_SRC

I will need to keep track of the current indentation while tangling
regular code lines, so that expansion of source block references
retain their original indentation.

#+NAME: Tangler
#+BEGIN_SRC haskell
type Indent = String
#+END_SRC

This indentation is kept in a ~TangleState~ object that gets updated
as tangling moves along. Two other pieces of information will be needed:
the original document, so I can expand references, and a stack of
source blocks currently being tangled, so I can access the currently
active set of Org properties.

#+NAME: Tangler
#+BEGIN_SRC haskell
data TangleState = TangleState
  { document :: Document
  , indent :: String
  , blocks :: Stack SourceBlock
  }
#+END_SRC

As the name implies, I treat this as a proper state, using the ~State~
monad.

#+NAME: Tangler
#+BEGIN_SRC haskell
type Tangler a = State TangleState a
#+END_SRC

To keep the global namespace pollution to a minimum, I will
make things that can be tangled into lines instances of a ~Tangle~ class.

#+NAME: Tangler
#+BEGIN_SRC haskell
class Tangle a where
  tangle :: a -> Tangler [Line]
#+END_SRC

Tangling source blocks is a matter of tangling all the block lines --
with an up-to-date state's block stack -- and adding an optional line
pragma indicating the location of the block's first line.

#+NAME: Tangler
#+BEGIN_SRC haskell
instance Tangle SourceBlock where
  tangle block = do
    modify (\s -> s{ blocks = push block (blocks s) })
    ls <- concat <$> mapM tangle (blockLines block)
    modify (\s -> s{ blocks = pop (blocks s) })
    return $ case headerArg ":comments" block of
      Just (YesNo True) -> LinePragma (blockLanguage block) (blockLocation block) : ls
      _ -> ls
#+END_SRC

Tangling code lines is a lot more complicated. The simple case is
tangling the empty line: all I need to do is to add the current
indentation to it.

#+NAME: Tangler
#+BEGIN_SRC haskell
instance Tangle CodeLine where
  tangle (CodeLine _ []) =
    (:[]) . CodeText . indent <$> get
  tangle (CodeLine _ elements) =
    <<Tangle code line with ~elements~>>
#+END_SRC

Tangling a code line is a matter of tangling all of its elements and
stitching them together. This is complicated by two things:

- A single element can result in multiple lines if it is a reference
  expansion. It is not uncommon for a "code line" to expand into a
  large part of the entire program.
- Those multiple lines have to be properly indented, which means I have to keep
  track of indentation as I go.

The mechanism used to handle those is a left fold that keeps track of
the current list of tangled lines. A new element is tangled and appended
to this list, and the indentation for the next element is given by
last line's length.


** Tangled Lines

#+NAME: Tangler
#+BEGIN_SRC haskell
unindent :: Indent -> Line -> Line
unindent i (CodeText s)
  | isPrefixOf i s = CodeText $ drop (length i) s
  | otherwise = CodeText s
unindent _ l = l
#+END_SRC

#+NAME: Tangler
#+BEGIN_SRC haskell
getIndent :: Tangler String
getIndent = indent <$> get

setIndentFrom :: String -> Tangler ()
setIndentFrom str = modify
  (\s -> s{ indent = replicate (length str) ' ' })

addIndentFrom :: String -> Tangler ()
addIndentFrom str = modify
  (\s -> s{ indent = indent s ++ replicate (length str) ' ' })
#+END_SRC


** Line Tangling

The lines are kept in reverse order until the end for performance
considerations. I need to merge the current last line to the next
first line, and finding the last line of a list in Haskell is an
expensive operation.

#+NAME: Tangle code line with ~elements~
#+BEGIN_SRC haskell
do
  state <- get
  let block = top (blocks state)
      ind   = indent state
      pos = case head elements of
              (Literal p _) -> p
              (SectionReference p _) -> p
      pragma = LinePragma (blockLanguage block) pos
  ls <- removeLeadingEmptyLine . reverse <$> foldlM revacc [CodeText ind] elements
  modify (\s -> s{ indent = ind })
  case headerArg ":comments" block of
    Just (YesNo True) -> return $ pragma : ls
    _ -> return ls
  where
    removeLeadingEmptyLine :: [Line] -> [Line]
    removeLeadingEmptyLine a@(CodeText l:p@(LinePragma _ _):ls)
      | all isSpace l = p:ls
      | otherwise = a
    removeLeadingEmptyLine a = a

    breakCodeText :: [Line] -> ([Line],[Line])
    breakCodeText = break (\case { (CodeText _) -> True; _ -> False })

    revacc :: [Line] -> CodeElement -> Tangler [Line]
    revacc acc element = do
      let (xxxpost, xxxpre) = breakCodeText acc
      case (xxxpost, xxxpre, element) of
        <<Tangle next code element>>
        _ -> error $ "unreachable element tangling case"
#+END_SRC

#+NAME: Tangle next code element
#+BEGIN_SRC haskell
([], (CodeText l:ls), Literal _ s) -> do
  addIndentFrom s
  return $ CodeText (l ++ s) : ls
#+END_SRC

If the literal appears right after a line pragma, then I need to
insert yet another line pragma to re-position the source code correctly.

#+NAME: Tangle next code element
#+BEGIN_SRC haskell
(_, _, Literal pos s) -> do
  i <- getIndent
  b <- top . blocks <$> get
  addIndentFrom s
  return $ LinePragma (blockLanguage b) pos : CodeText (i ++ s) : acc
#+END_SRC

#+NAME: Tangle next code element
#+BEGIN_SRC haskell
(post, (CodeText l:ls), SectionReference pos name) -> do
  bs <- <<Gather code blocks named ~name~>> :: Tangler [SourceBlock]
  when (null bs) (error $ "source block not defined anywhere: " ++ show name)
  tangledLines <- concat <$> mapM tangle bs :: Tangler [Line]
  let (pre, (CodeText first : rest)) = breakCodeText tangledLines
  acc' <- case (pre, post) of
    ([], []) -> do
      i <- getIndent
      let (CodeText first') = unindent i (CodeText first)
      addIndentFrom first'
      return $ reverse rest ++ [CodeText(l ++ first')] ++ ls
    _ -> do
      setIndentFrom first
      return $ reverse tangledLines ++ acc
  block <- top . blocks <$> get
  case headerArg ":comments" block of
    Just (YesNo True) -> return $ LinePragma (blockLanguage block) pos : acc'
    _ -> return acc'
#+END_SRC

Tangling of code parts is the last piece of the puzzle. Literals are
easy, but code blocks need to have their first lines be /not/
indented, so one can have proper "inline" code blocks, such as

#+BEGIN_SRC c :tangle no
int main(void) { <<do everything>>; return 0; }
#+END_SRC

#+NAME: Gather code blocks named ~name~
#+BEGIN_SRC haskell
filter (\b -> case (blockName b) of
               Nothing -> False
               Just t -> t == name)
  . mapMaybe sectionSourceBlock
  . orgSections
  . document
  <$> get
#+END_SRC

#+NAME: Imports
#+BEGIN_SRC haskell
import qualified System.Directory as D
import qualified System.Environment as Env
import qualified System.FilePath as F
import qualified System.Posix.Files as F
import qualified System.Posix.Types as F
#+END_SRC

#+NAME: stack-packages
#+BEGIN_SRC shell
--package filepath
--package directory
--package unix
#+END_SRC

#+NAME: Tangler
#+BEGIN_SRC haskell
tangleFile :: Options -> Document -> (FilePath, [SourceBlock]) -> IO ()
tangleFile opts _ (fp, []) =
  logM (logLevel opts) Warning $ "Not writing empty output file (" ++ fp ++ ")"
tangleFile opts doc (fp, bs) = do
  let ls = concatMap
           (\b -> fst $ runState (tangle b) TangleState{ document = doc, indent = [], blocks = Stack [] })
           bs
      ls' = <<Remove redundant line pragmas>> ls
      contents = concatMap show ls'
      block = head bs
  logM (logLevel opts) Info $ "Writing the output file (" ++ fp ++ ")"
  if dryRun opts
    then logM (logLevel opts) Info contents
    else do
      let dir = F.takeDirectory fp
      when (mkDir && dir /= ".") $ D.createDirectoryIfMissing True dir

      exists <- F.fileExist fp
      when exists $ F.removeLink fp

      writeFile fp contents
      case headerArg ":tangle-mode" block of
        Nothing -> return ()
        Just expr -> do
          let mode = fileMode expr
          F.setFileMode fp mode
  where
    mkDir = case headerArg ":mkdirp" (head bs) of
              Just (YesNo x) -> x
              _ -> False
#+END_SRC

