* Tangling

#+BEGIN_SRC haskell :tangle "bin/cctangle.hs" :tangle-mode (identity #o444)
<<Common-ccweb-code>>
<<Tangler>>
#+END_SRC

#+NAME: Tangler
#+BEGIN_SRC haskell
type Indent = String
#+END_SRC

#+NAME: Tangler
#+BEGIN_SRC haskell
data Line = LinePragma String P.SourcePos | Raw String

instance Show Line where
  show (Raw str) = str ++ "\n"
  show (LinePragma lang pos) = case linePragma lang pos of
                               [] -> ""
                               s -> s ++ "\n"

unindent :: Indent -> Line -> Line
unindent i (Raw s)
  | isPrefixOf i s = Raw $ drop (length i) s
  | otherwise = Raw s
unindent _ l = l
#+END_SRC

#+NAME: Tangler
#+BEGIN_SRC haskell
data TangleState = TangleState
  { document :: Document
  , indent :: String
  , blocks :: Stack SourceBlock
  }
#+END_SRC

#+NAME: Tangler
#+BEGIN_SRC haskell
type Tangler a = State TangleState a
#+END_SRC

#+NAME: Tangler
#+BEGIN_SRC haskell
getIndent :: Tangler String
getIndent = indent <$> get

setIndentFrom :: String -> Tangler ()
setIndentFrom str = modify
  (\s -> s{ indent = replicate (length str) ' ' })

addIndentFrom :: String -> Tangler ()
addIndentFrom str = modify
  (\s -> s{ indent = indent s ++ replicate (length str) ' ' })
#+END_SRC


#+NAME: Tangler
#+BEGIN_SRC haskell
class Tangle a where
  tangle :: a -> Tangler [Line]
#+END_SRC

Tangling a code block results in a list of /lines/. The first line is
not indented, and is appended to the previous code part on the same
line. The last line will be prepended to the next code part on the
same line.

#+NAME: Tangler
#+BEGIN_SRC haskell
instance Tangle SourceBlock where
  tangle block = do
    modify (\s -> s{ blocks = push block (blocks s) })
    ls <- concat <$> mapM tangle (blockLines block)
    modify (\s -> s{ blocks = pop (blocks s) })
    let pragma = LinePragma (blockLanguage block) (blockLocation block)
    case headerArg ":comments" block of
      Just (YesNo True) -> return (pragma : ls)
      _ -> return ls
#+END_SRC

Tangling a code line is a matter of tangling all of its elements and
stitching them together. This is complicated by two things:

- A single element can result in multiple lines if it is a reference
  expansion. It is not uncommon for a "code line" to expand into a
  large part of the entire program.
- Those lines have to be properly indented, which means I have to keep
  track of indentation as I go.

The mechanism used to handle those is a left fold that keeps track of
the current list of tangled lines. A new element is tangled and appended
to this list, and the indentation for the next element is given by the
last line.

The lines are kept in reverse order until the end for performance
considerations. I need to merge the current last line to the next
first line, and finding the last line of a list in Haskell is an
expensive operation.

#+NAME: Tangler
#+BEGIN_SRC haskell
instance Tangle CodeLine where
  tangle (CodeLine _ []) = do
    ind <- indent <$> get
    return [Raw ind]
  tangle (CodeLine _ elements) = do
    state <- get
    let block = top (blocks state)
        ind   = indent state
        pos = case head elements of
                (Literal p _) -> p
                (SectionReference p _) -> p
        pragma = LinePragma (blockLanguage block) pos
    ls <- removeLeadingEmptyLine . reverse <$> foldlM revacc [Raw ind] elements
    modify (\s -> s{ indent = ind })
    case headerArg ":comments" block of
      Just (YesNo True) -> return $ pragma : ls
      _ -> return ls
      where
        removeLeadingEmptyLine :: [Line] -> [Line]
        removeLeadingEmptyLine a@(Raw l:p@(LinePragma _ _):ls)
          | all isSpace l = p:ls
          | otherwise = a
        removeLeadingEmptyLine a = a

        breakRaw :: [Line] -> ([Line],[Line])
        breakRaw = break (\case { (Raw _) -> True; _ -> False })

        revacc :: [Line] -> CodeElement -> Tangler [Line]
        revacc acc element = do
          let (xxxpost, xxxpre) = breakRaw acc
          case (xxxpost, xxxpre, element) of
            <<Tangle next code element>>
            _ -> error $ "unreachable element tangling case"
#+END_SRC

#+NAME: Tangle next code element
#+BEGIN_SRC haskell
([], (Raw l:ls), Literal _ s) -> do
  addIndentFrom s
  return $ Raw (l ++ s) : ls
#+END_SRC

If the literal appears right after a line pragma, then I need to
insert yet another line pragma to re-position the source code correctly.

#+NAME: Tangle next code element
#+BEGIN_SRC haskell
(_, _, Literal pos s) -> do
  i <- getIndent
  b <- top . blocks <$> get
  addIndentFrom s
  return $ LinePragma (blockLanguage b) pos : Raw (i ++ s) : acc
#+END_SRC

#+NAME: Tangle next code element
#+BEGIN_SRC haskell
(post, (Raw l:ls), SectionReference pos name) -> do
  bs <- <<Gather code blocks named ~name~>> :: Tangler [SourceBlock]
  when (null bs) (error $ "source block not defined anywhere: " ++ show name)
  tangledLines <- concat <$> mapM tangle bs :: Tangler [Line]
  let (pre, (Raw first : rest)) = breakRaw tangledLines
  acc' <- case (pre, post) of
    ([], []) -> do
      i <- getIndent
      let (Raw first') = unindent i (Raw first)
      addIndentFrom first'
      return $ reverse rest ++ [Raw(l ++ first')] ++ ls
    _ -> do
      setIndentFrom first
      return $ reverse tangledLines ++ acc
  block <- top . blocks <$> get
  case headerArg ":comments" block of
    Just (YesNo True) -> return $ LinePragma (blockLanguage block) pos : acc'
    _ -> return acc'
#+END_SRC

Tangling of code parts is the last piece of the puzzle. Literals are
easy, but code blocks need to have their first lines be /not/
indented, so one can have proper "inline" code blocks, such as

#+BEGIN_SRC c :tangle no
int main(void) { <<do everything>>; return 0; }
#+END_SRC

#+NAME: Gather code blocks named ~name~
#+BEGIN_SRC haskell
filter (\b -> case (blockName b) of
               Nothing -> False
               Just t -> t == name)
  . mapMaybe sectionSourceBlock
  . orgSections
  . document
  <$> get
#+END_SRC

#+NAME: Imports
#+BEGIN_SRC haskell
import Numeric (showOct)
import qualified System.Directory as D
import qualified System.Environment as Env
import qualified System.FilePath as F
import qualified System.Posix.Files as F
import qualified System.Posix.Types as F
#+END_SRC

#+NAME: stack-packages
#+BEGIN_SRC shell
--package filepath
--package directory
--package unix
#+END_SRC

#+NAME: Tangler
#+BEGIN_SRC haskell
tangleFile :: Options -> Document -> (FilePath, [SourceBlock]) -> IO ()
tangleFile opts _ (fp, []) =
  logM (logLevel opts) Warning $ "* File " ++ fp ++ " seems to be empty."
tangleFile opts doc (fp, bs) = do
  let ls = concatMap
           (\b -> fst $ runState (tangle b) TangleState{ document = doc, indent = [], blocks = Stack [] })
           bs
      ls' = <<Remove redundant line pragmas from ~ls~>>
      contents = concatMap show ls'
      block = head bs
  logM (logLevel opts) Info $ "* Writing file " ++ fp ++ "..."
  if dryRun opts
    then ( logM (logLevel opts) Info "** Dry-run: writing to stdout"
           >> logM (logLevel opts) Info contents
         )
    else do
      let dir = F.takeDirectory fp
      when (mkDir && dir /= ".") $ do
        logM (logLevel opts) Info $ "** Creating missing directories..."
        D.createDirectoryIfMissing True dir
      exists <- F.fileExist fp
      when exists $ do
        logM (logLevel opts) Info $ "** Removing pre-existing file..."
        F.removeLink fp
      logM (logLevel opts) Info $
        "** Writing file contents..."
      writeFile fp contents
      case headerArg ":tangle-mode" block of
        Nothing -> return ()
        Just expr -> do
          let mode = fileMode expr
          logM (logLevel opts) Info $
            "** Setting file mode to #o" ++ showOct mode "..."
          F.setFileMode fp mode
  where
    mkDir = case headerArg ":mkdirp" (head bs) of
              Just (YesNo x) -> x
              _ -> False
#+END_SRC

#+NAME: Remove redundant line pragmas from ~ls~
#+BEGIN_SRC haskell
foldr (\x xs -> let a = (x:xs) in case a of
          (LinePragma _ _ : LinePragma _ _ : _) -> xs
          (LinePragma _ p1 : h : LinePragma _ p2 : xs') ->
            if P.sourceName p1 == P.sourceName p2 && P.sourceLine p1 + 1 == P.sourceLine p2
            then x : h : xs'
            else a
          _ -> a)
      []
      ls
#+END_SRC

#+NAME: Tangler
#+BEGIN_SRC haskell
main :: IO ()
main = do
  opts <- O.execParser optParser
  logM (logLevel opts) Debug "* Command line options:"
  logM (logLevel opts) Debug $ PP.render (pretty opts)

  ingested <- fromList <$> ingest (inputFile opts) :: IO OrgFile
  logM (logLevel opts) Debug $ PP.render (pretty ingested)

  hname <- getHostName
  let org = fromEither
            $ P.runParser
            (parse :: Parser Document)
            initialParserState{ hostName = hname }
            (inputFile opts)
            ingested
  logM (logLevel opts) Debug $ PP.render (pretty org)

  home <- Env.getEnv "HOME"
  let fs = <<Gather sections to tangle to files>> :: [(FilePath, [SourceBlock])]
  when (listInputFiles opts) $ <<List input files>>
  when (listOutputFiles opts) $ <<List output files>>

  mapM_ (tangleFile opts org) fs
  where
    optParser = O.info (tanglerOptionParser <**> O.helper)
      ( O.fullDesc
      <> O.progDesc "Tangle the input FILE"
      <> O.header "cctangle - A literate programming tangler" )
#+END_SRC

#+NAME: Gather sections to tangle to files
#+BEGIN_SRC haskell
map (\bs -> (fst (head bs), map snd bs))
  . groupWith fst
  . sortWith fst
  . map (\(fp,b) -> case fp of
            ('~':xs) -> (home ++ xs, b)
            _ -> (fp, b))
  . mapMaybe (\b -> (\fp -> (fp, b)) <$> blockFile b)
  . mapMaybe sectionSourceBlock
  $ orgSections org
#+END_SRC

#+NAME: List input files
#+BEGIN_SRC haskell
mapM_ putStrLn (
  nub . sort .
  map (\(OrgLine p _) -> P.sourceName p) $ (toList ingested)
)
#+END_SRC

#+NAME: List output files
#+BEGIN_SRC haskell
mapM_ putStrLn (map fst fs)
#+END_SRC

** Line numbers

#+NAME: Tangler
#+BEGIN_SRC haskell
linePragma :: String -> P.SourcePos -> String
linePragma "haskell" pos =
  unwords ["{-# LINE", show (P.sourceLine pos), "\"" ++ P.sourceName pos ++ "\"", "#-}" ]
linePragma "c" pos =
  unwords ["#line", show (P.sourceLine pos), "\"" ++ P.sourceName pos ++ "\"" ]
linePragma "c++" pos =
  linePragma "c" pos
linePragma _ _ = []
#+END_SRC

